Veins Framework: Move Class Reference
Move Class Reference
Class to store object position and movement.
#include <Move.h>
Public Member Functions
Move ()
Move (const Move &mSrc)
double getSpeed () const
Returns the current speed.
void setSpeed (double speed)
Sets the current speed in meters per second.
const Coord & getStartPos () const
Returns the start position.
simtime_t_cref getStartTime () const
Returns start time, i.e.
void setStart (const Coord &startPos, simtime_t_cref startTime)
Sets start position (components in meters) and start time.
void setStart (const Coord &startPos)
Sets start position to passed value (components in meters), start time will be set to current simulation-time.
const Coord & getDirection () const
Returns the direction vector (which is unit less, because of normalization).
const Coord & getOrientation () const
Returns the orientation vector, i.e.
void setOrientationByVector (const Coord &orientation)
Sets the orientation to the passed vector.
void setDirectionByVector (const Coord &direction)
Sets the direction to the passed vector, which must be already normalized or the 0-vector.
void setDirectionByTarget (const Coord &target)
Sets the direction to the normalized vector pointing from the current start position to the passed target point.
virtual Coord getPositionAt (simtime_t_cref actualTime=simTime()) const
Returns the position of the Move (Host) at the specified point in time.
virtual const Coord & getCurrentPosition () const
std::string info () const
Returns information about the current state.
Protected Attributes
Coord startPos
Start position of the host (in meters)
Coord lastPos
Last position which was set.
simtime_t startTime
start time at which host started at startPos
Coord orientation
orientation the host is pointing to
Coord direction
direction the host is moving to, must be normalized
double speed
speed of the host in meters per second
Detailed Description
Class to store object position and movement.
Author
Andreas Koepke, Michael Swigulski
Constructor & Destructor Documentation
Move::Move () inline
         : startPos()
         , lastPos(0.0,0.0,DBL_MAX)
         , startTime()
         , orientation()
         , direction()
         , speed(0.0)
     {}
Move::Move (const Move & mSrc) inline
         : startPos(mSrc.startPos)
         , lastPos(mSrc.lastPos)
         , startTime(mSrc.startTime)
         , orientation(mSrc.orientation)
         , direction(mSrc.direction)
         , speed(mSrc.speed)
     {}
Member Function Documentation
virtual const Coord& Move::getCurrentPosition () const inline virtual
Referenced by Veins::TraCIMobility::changePosition(), Veins::TraCIMobility::initialize(), and Veins::TraCIMobility::preInitialize().
     {
         if (lastPos.z != DBL_MAX)
                 return lastPos;
         return startPos;
     }
const Coord& Move::getDirection () const inline
Returns the direction vector (which is unit less, because of normalization).
Referenced by BaseMobility::checkIfOutside(), and BaseMobility::goToBorder().
         {
                 return direction;
         }
const Coord& Move::getOrientation () const inline
Returns the orientation vector, i.e.
the direction the host is pointing in. The difference to direction is that the x and y components are never both 0, which is important for the calculation of the antenna gain. At simulation start, it is initialized with a (user defined) value. If the host stops during simulation, the last direction is stored in the orientation field.
{
             return orientation;
         }
virtual Coord Move::getPositionAt (simtime_t_cref actualTime = simTime()) const inline virtual
Returns the position of the Move (Host) at the specified point in time.
It is intended to be passed simTime() as actualTime and returns the actual position.
Assumes that direction represents a normalized vector (length equals 1.0). Further this function does not check whether the given time point is before the startTime of the actual move pattern. So in this case one might obtain an unintended result.
Referenced by Veins::TraCIMobility::getPositionAt().
     {
         // if speed is very close to 0.0, the host is practically standing still
         if ( FWMath::close(speed, 0.0) ) return startPos;
         // otherwise: actualPos = startPos + ( direction * v * t )
         return startPos + ( direction * speed * SIMTIME_DBL(actualTime - startTime) );
     }
double Move::getSpeed () const inline
Returns the current speed.
Referenced by BaseMobility::handleIfOutside(), BaseMobility::handleSelfMsg(), BaseMobility::initialize(), and LinearMobility::makeMove().
         {
                 return speed;
         }
const Coord& Move::getStartPos () const inline
Returns the start position.
Referenced by Veins::TraCIMobility::changePosition(), BaseMobility::checkIfOutside(), Veins::TraCIMobility::fixIfHostGetsOutside(), BaseMobility::goToBorder(), BaseMobility::handleBorderMsg(), BaseMobility::handleIfOutside(), LinearMobility::initialize(), BaseMobility::initialize(), LinearMobility::makeMove(), and BaseMobility::updatePosition().
         {
                 return startPos;
         }
simtime_t_cref Move::getStartTime () const inline
Returns start time, i.e.
time point of the start at start position.
         {
                 return startTime;
         }
std::string Move::info () const inline
Returns information about the current state.
Referenced by BaseMobility::handleBorderMsg(), LinearMobility::makeMove(), and BaseMobility::updatePosition().
{
         std::ostringstream ost;
         ost << " HostMove "
             << " startPos: " << startPos.info()
             << " direction: " << direction.info()
             << " orientation: " << orientation.info()
             << " startTime: " << startTime
             << " speed: " << speed;
         return ost.str();
     }
void Move::setDirectionByTarget (const Coord & target) inline
Sets the direction to the normalized vector pointing from the current start position to the passed target point.
NOTE: The target point must not be the current start position or too close to it.
Referenced by LinearMobility::makeMove().
         {
         direction = target - startPos;
         assert( !FWMath::close(direction.length(), 0.0) );
         direction /= direction.length();
         // only if one of the x or y components is nonzero, also set orientation to
         // the new direction
         if (direction.x != 0 || direction.y != 0) {
             setOrientationByVector(direction);
         }
     }
void Move::setDirectionByVector (const Coord & direction) inline
Sets the direction to the passed vector, which must be already normalized or the 0-vector.
Referenced by Veins::TraCIMobility::changePosition(), BaseMobility::handleBorderMsg(), Veins::TraCIMobility::initialize(), BaseMobility::initialize(), and Veins::TraCIMobility::preInitialize().
         {
                 assert( FWMath::close(direction.squareLength(), 1.0)
                                 || FWMath::close(direction.squareLength(), 0.0));
                 this->direction = direction;
                 // only if one of the x or y components is nonzero, also set orientation to
                 // the given value
                 if (direction.x != 0 || direction.y != 0) {
                     setOrientationByVector(direction);
                 }
         }
void Move::setOrientationByVector (const Coord & orientation) inline
Sets the orientation to the passed vector.
At least one of the x or y component has to be nonzero.
Referenced by BaseMobility::initialize().
{
             assert(orientation.x != 0 || orientation.y != 0);
             this->orientation = orientation;
         }
void Move::setSpeed (double speed) inline
Sets the current speed in meters per second.
Referenced by Veins::TraCIMobility::changePosition(), LinearMobility::initialize(), Veins::TraCIMobility::initialize(), BaseMobility::initialize(), LinearMobility::makeMove(), and Veins::TraCIMobility::preInitialize().
         {
                 this->speed = speed;
         }
void Move::setStart (const Coord & startPos, simtime_t_cref startTime) inline
Sets start position (components in meters) and start time.
Referenced by Veins::TraCIMobility::changePosition(), BaseMobility::handleBorderMsg(), Veins::TraCIMobility::initialize(), BaseMobility::initialize(), LinearMobility::makeMove(), and Veins::TraCIMobility::preInitialize().
         {
                 this->lastPos   = startPos;
                 this->startPos  = startPos;
                 this->startTime = startTime;
         }
void Move::setStart (const Coord & startPos) inline
Sets start position to passed value (components in meters), start time will be set to current simulation-time.
         {
                 setStart(startPos, simTime());
         }
Member Data Documentation
Coord Move::direction protected
direction the host is moving to, must be normalized
Coord Move::lastPos protected
Last position which was set.
Coord Move::orientation protected
orientation the host is pointing to
double Move::speed protected
speed of the host in meters per second
Coord Move::startPos protected
Start position of the host (in meters)
simtime_t Move::startTime protected
start time at which host started at startPos
The documentation for this class was generated from the following file:
Move.h