Veins Framework: AccessModuleWrap< T > Class Template Reference
AccessModuleWrap< T > Class Template Reference
Finds and returns the pointer to a module of type T.
#include <FindModule.h>
Public Types
typedef T wrapType
Public Member Functions
AccessModuleWrap ()
T *const get (cModule *const from=NULL)
Private Attributes
T * pModule
Detailed Description
template<typename T = cModule>
class AccessModuleWrap< T >
Finds and returns the pointer to a module of type T.
Uses FindModule<>::findSubModule(), FindModule<>::findHost(). See usage e.g. at ChannelAccess.
Member Typedef Documentation
template<typename T = cModule> typedef T AccessModuleWrap< T >::wrapType
Constructor & Destructor Documentation
template<typename T = cModule> AccessModuleWrap< T >::AccessModuleWrap () inline
                                    : pModule(NULL)
                 {}
Member Function Documentation
template<typename T = cModule> T* const AccessModuleWrap< T >::get (cModule *const from = NULL) inline
Referenced by BasePhyLayer::filterSignal(), Veins::ChannelAccess::getMobilityModule(), and BasePhyLayer::handleUpperMessage().
                 {
                         if (!pModule) {
                                 pModule = FindModule<T*>::findSubModule( FindModule<>::findHost(from != NULL ? from : getSimulation()->getContextModule()) );
                         }
                         return pModule;
                 }
Member Data Documentation
template<typename T = cModule> T* AccessModuleWrap< T >::pModule private
Referenced by AccessModuleWrap< T >::get().
The documentation for this class was generated from the following file:
FindModule.h