Veins Framework: WaveAppToMac1609_4Interface Class Reference
WaveAppToMac1609_4Interface Class Reference abstract
Interface between WaveApplication Layer and Mac1609_4.
#include <WaveAppToMac1609_4Interface.h>
Public Member Functions
virtual bool isChannelSwitchingActive ()=0
virtual simtime_t getSwitchingInterval ()=0
virtual bool isCurrentChannelCCH ()=0
virtual void changeServiceChannel (int channelNumber)=0
virtual ~WaveAppToMac1609_4Interface ()
Detailed Description
Interface between WaveApplication Layer and Mac1609_4.
Author
David Eckhoff
Constructor & Destructor Documentation
virtual WaveAppToMac1609_4Interface::~WaveAppToMac1609_4Interface () inline virtual
 {} ;
Member Function Documentation
virtual void WaveAppToMac1609_4Interface::changeServiceChannel (int channelNumber) pure virtual
Implemented in Mac1609_4.
Referenced by TraCIDemoRSU11p::onWSA(), and BaseWaveApplLayer::startService().
virtual simtime_t WaveAppToMac1609_4Interface::getSwitchingInterval () pure virtual
Implemented in Mac1609_4.
Referenced by BaseWaveApplLayer::computeAsynchronousSendingTime(), and BaseWaveApplLayer::initialize().
virtual bool WaveAppToMac1609_4Interface::isChannelSwitchingActive () pure virtual
Implemented in Mac1609_4.
Referenced by BaseWaveApplLayer::initialize().
virtual bool WaveAppToMac1609_4Interface::isCurrentChannelCCH () pure virtual
Implemented in Mac1609_4.
Referenced by BaseWaveApplLayer::computeAsynchronousSendingTime().
The documentation for this class was generated from the following file:
WaveAppToMac1609_4Interface.h