Veins Framework: Veins::ObstacleControl Class Reference
Veins::ObstacleControl Class Reference
#include <ObstacleControl.h>
Classes
struct CacheKey
Public Member Functions
~ObstacleControl ()
void initialize (int stage)
int numInitStages () const
void finish ()
void handleMessage (cMessage *msg)
void handleSelfMsg (cMessage *msg)
void addFromXml (cXMLElement *xml)
void addFromTypeAndShape (std::string id, std::string typeId, std::vector< Coord > shape)
void add (Obstacle obstacle)
void erase (const Obstacle *obstacle)
bool isTypeSupported (std::string type)
double getAttenuationPerCut (std::string type)
double getAttenuationPerMeter (std::string type)
double calculateAttenuation (const Coord &senderPos, const Coord &receiverPos) const
calculate additional attenuation by obstacles, return signal strength
Protected Types
enum { GRIDCELL_SIZE = 1024 }
typedef std::list< Obstacle * > ObstacleGridCell
typedef std::vector
< ObstacleGridCell > ObstacleGridRow
typedef std::vector
< ObstacleGridRow > Obstacles
typedef std::map< CacheKey,
double > CacheEntries
Protected Attributes
bool debug
whether to emit debug messages
cXMLElement * obstaclesXml
obstacles to add at startup
Obstacles obstacles
AnnotationManager * annotations
AnnotationManager::Group * annotationGroup
std::map< std::string, double > perCut
std::map< std::string, double > perMeter
CacheEntries cacheEntries
Member Typedef Documentation
typedef std::map<CacheKey, double> Veins::ObstacleControl::CacheEntries protected
typedef std::list<Obstacle*> Veins::ObstacleControl::ObstacleGridCell protected
typedef std::vector<ObstacleGridCell> Veins::ObstacleControl::ObstacleGridRow protected
typedef std::vector<ObstacleGridRow> Veins::ObstacleControl::Obstacles protected
Member Enumeration Documentation
anonymous enum protected
Enumerator
GRIDCELL_SIZE
 { GRIDCELL_SIZE = 1024 };
Constructor & Destructor Documentation
ObstacleControl::~ObstacleControl ()
{
 }
Member Function Documentation
void ObstacleControl::add (Obstacle obstacle)
Referenced by addFromTypeAndShape(), and addFromXml().
{
         Obstacle* o = new Obstacle(obstacle);
         size_t fromRow = std::max(0, int(o->getBboxP1().x / GRIDCELL_SIZE));
         size_t toRow = std::max(0, int(o->getBboxP2().x / GRIDCELL_SIZE));
         size_t fromCol = std::max(0, int(o->getBboxP1().y / GRIDCELL_SIZE));
         size_t toCol = std::max(0, int(o->getBboxP2().y / GRIDCELL_SIZE));
         for (size_t row = fromRow; row <= toRow; ++row) {
                 for (size_t col = fromCol; col <= toCol; ++col) {
                         if (obstacles.size() < col+1) obstacles.resize(col+1);
                         if (obstacles[col].size() < row+1) obstacles[col].resize(row+1);
                         (obstacles[col])[row].push_back(o);
                 }
         }
         // visualize using AnnotationManager
         if (annotations) o->visualRepresentation = annotations->drawPolygon(o->getShape(), "red", annotationGroup);
         cacheEntries.clear();
 }
void ObstacleControl::addFromTypeAndShape (std::string id, std::string typeId, std::vector< Coord > shape)
Referenced by Veins::TraCIScenarioManager::init_traci().
{
         if (!isTypeSupported(typeId)) {
                 throw cRuntimeError("Unsupported obstacle type: \"%s\"", typeId.c_str());
         }
         Obstacle obs(id, typeId, getAttenuationPerCut(typeId), getAttenuationPerMeter(typeId));
         obs.setShape(shape);
         add(obs);
 }
void ObstacleControl::addFromXml (cXMLElement * xml)
Referenced by initialize().
{
         std::string rootTag = xml->getTagName();
         if (rootTag != "obstacles") {
                 throw cRuntimeError("Obstacle definition root tag was \"%s\", but expected \"obstacles\"", rootTag.c_str());
         }
         cXMLElementList list = xml->getChildren();
         for (cXMLElementList::const_iterator i = list.begin(); i != list.end(); ++i) {
                 cXMLElement* e = *i;
                 std::string tag = e->getTagName();
                 if (tag == "type") {
                         // <type id="building" db-per-cut="9" db-per-meter="0.4" />
                         ASSERT(e->getAttribute("id"));
                         std::string id = e->getAttribute("id");
                         ASSERT(e->getAttribute("db-per-cut"));
                         std::string perCutParS = e->getAttribute("db-per-cut");
                         double perCutPar = strtod(perCutParS.c_str(), 0);
                         ASSERT(e->getAttribute("db-per-meter"));
                         std::string perMeterParS = e->getAttribute("db-per-meter");
                         double perMeterPar = strtod(perMeterParS.c_str(), 0);
                         perCut[id] = perCutPar;
                         perMeter[id] = perMeterPar;
                 }
                 else if (tag == "poly") {
                         // <poly id="building#0" type="building" color="#F00" shape="16,0 8,13.8564 -8,13.8564 -16,0 -8,-13.8564 8,-13.8564" />
                         ASSERT(e->getAttribute("id"));
                         std::string id = e->getAttribute("id");
                         ASSERT(e->getAttribute("type"));
                         std::string type = e->getAttribute("type");
                         ASSERT(e->getAttribute("color"));
                         std::string color = e->getAttribute("color");
                         ASSERT(e->getAttribute("shape"));
                         std::string shape = e->getAttribute("shape");
                         Obstacle obs(id, type, getAttenuationPerCut(type), getAttenuationPerMeter(type));
                         std::vector<Coord> sh;
                         cStringTokenizer st(shape.c_str());
                         while (st.hasMoreTokens()) {
                                 std::string xy = st.nextToken();
                                 std::vector<double> xya = cStringTokenizer(xy.c_str(), ",").asDoubleVector();
                                 ASSERT(xya.size() == 2);
                                 sh.push_back(Coord(xya[0], xya[1]));
                         }
                         obs.setShape(sh);
                         add(obs);
                 }
                 else {
                         throw cRuntimeError("Found unknown tag in obstacle definition: \"%s\"", tag.c_str());
                 }
         }
 }
double ObstacleControl::calculateAttenuation (const Coord & senderPos, const Coord & receiverPos) const
calculate additional attenuation by obstacles, return signal strength
Referenced by SimpleObstacleShadowing::filterSignal().
{
         Enter_Method_Silent();
         if ((perCut.size() == 0) || (perMeter.size() == 0)) {
                 throw cRuntimeError("Unable to use SimpleObstacleShadowing: No obstacle types have been configured");
         }
         if (obstacles.size() == 0) {
                 throw cRuntimeError("Unable to use SimpleObstacleShadowing: No obstacles have been added");
         }
         // return cached result, if available
         CacheKey cacheKey(senderPos, receiverPos);
         CacheEntries::const_iterator cacheEntryIter = cacheEntries.find(cacheKey);
         if (cacheEntryIter != cacheEntries.end()) return cacheEntryIter->second;
         // calculate bounding box of transmission
         Coord bboxP1 = Coord(std::min(senderPos.x, receiverPos.x), std::min(senderPos.y, receiverPos.y));
         Coord bboxP2 = Coord(std::max(senderPos.x, receiverPos.x), std::max(senderPos.y, receiverPos.y));
         size_t fromRow = std::max(0, int(bboxP1.x / GRIDCELL_SIZE));
         size_t toRow = std::max(0, int(bboxP2.x / GRIDCELL_SIZE));
         size_t fromCol = std::max(0, int(bboxP1.y / GRIDCELL_SIZE));
         size_t toCol = std::max(0, int(bboxP2.y / GRIDCELL_SIZE));
         std::set<Obstacle*> processedObstacles;
         double factor = 1;
         for (size_t col = fromCol; col <= toCol; ++col) {
                 if (col >= obstacles.size()) break;
                 for (size_t row = fromRow; row <= toRow; ++row) {
                         if (row >= obstacles[col].size()) break;
                         const ObstacleGridCell& cell = (obstacles[col])[row];
                         for (ObstacleGridCell::const_iterator k = cell.begin(); k != cell.end(); ++k) {
                                 Obstacle* o = *k;
                                 if (processedObstacles.find(o) != processedObstacles.end()) continue;
                                 processedObstacles.insert(o);
                                 // bail if bounding boxes cannot overlap
                                 if (o->getBboxP2().x < bboxP1.x) continue;
                                 if (o->getBboxP1().x > bboxP2.x) continue;
                                 if (o->getBboxP2().y < bboxP1.y) continue;
                                 if (o->getBboxP1().y > bboxP2.y) continue;
                                 double factorOld = factor;
                                 factor *= o->calculateAttenuation(senderPos, receiverPos);
                                 // draw a "hit!" bubble
                                 if (annotations && (factor != factorOld)) annotations->drawBubble(o->getBboxP1(), "hit");
                                 // bail if attenuation is already extremely high
                                 if (factor < 1e-30) break;
                         }
                 }
         }
         // cache result
         if (cacheEntries.size() >= 1000) cacheEntries.clear();
         cacheEntries[cacheKey] = factor;
         return factor;
 }
void ObstacleControl::erase (const Obstacle * obstacle)
Referenced by finish().
{
         for (Obstacles::iterator i = obstacles.begin(); i != obstacles.end(); ++i) {
                 for (ObstacleGridRow::iterator j = i->begin(); j != i->end(); ++j) {
                         for (ObstacleGridCell::iterator k = j->begin(); k != j->end(); ) {
                                 Obstacle* o = *k;
                                 if (o == obstacle) {
                                         k = j->erase(k);
                                 } else {
                                         ++k;
                                 }
                         }
                 }
         }
         if (annotations && obstacle->visualRepresentation) annotations->erase(obstacle->visualRepresentation);
         delete obstacle;
         cacheEntries.clear();
 }
void ObstacleControl::finish ()
{
         for (Obstacles::iterator i = obstacles.begin(); i != obstacles.end(); ++i) {
                 for (ObstacleGridRow::iterator j = i->begin(); j != i->end(); ++j) {
                         while (j->begin() != j->end()) erase(*j->begin());
                 }
         }
         obstacles.clear();
 }
double ObstacleControl::getAttenuationPerCut (std::string type)
Referenced by addFromTypeAndShape(), and addFromXml().
{
         if (perCut.find(type) != perCut.end()) return perCut[type];
         else {
                 error("Obstacle type %s unknown", type.c_str());
                 return -1;
         }
 }
double ObstacleControl::getAttenuationPerMeter (std::string type)
Referenced by addFromTypeAndShape(), and addFromXml().
{
         if (perMeter.find(type) != perMeter.end()) return perMeter[type];
         else {
                 error("Obstacle type %s unknown", type.c_str());
                 return -1;
         }
 }
void ObstacleControl::handleMessage (cMessage * msg)
{
         if (msg->isSelfMessage()) {
                 handleSelfMsg(msg);
                 return;
         }
         error("ObstacleControl doesn't handle messages from other modules");
 }
void ObstacleControl::handleSelfMsg (cMessage * msg)
Referenced by handleMessage().
{
         error("ObstacleControl doesn't handle self-messages");
 }
void ObstacleControl::initialize (int stage)
{
         if (stage == 1) {
                 debug = par("debug");
                 obstacles.clear();
                 cacheEntries.clear();
                 annotations = AnnotationManagerAccess().getIfExists();
                 if (annotations) annotationGroup = annotations->createGroup("obstacles");
                 obstaclesXml = par("obstacles");
                 addFromXml(obstaclesXml);
         }
 }
bool ObstacleControl::isTypeSupported (std::string type)
Referenced by addFromTypeAndShape(), and Veins::TraCIScenarioManager::init_traci().
{
         //the type of obstacle is supported if there are attenuation values for borders and interior
         return (perCut.find(type) != perCut.end()) && (perMeter.find(type) != perMeter.end());
 }
int Veins::ObstacleControl::numInitStages () const inline
 { return 2; }
Member Data Documentation
AnnotationManager::Group* Veins::ObstacleControl::annotationGroup protected
Referenced by add(), and initialize().
AnnotationManager* Veins::ObstacleControl::annotations protected
Referenced by add(), calculateAttenuation(), erase(), and initialize().
CacheEntries Veins::ObstacleControl::cacheEntries mutable protected
Referenced by add(), calculateAttenuation(), erase(), and initialize().
bool Veins::ObstacleControl::debug protected
whether to emit debug messages
Referenced by initialize().
Obstacles Veins::ObstacleControl::obstacles protected
Referenced by add(), calculateAttenuation(), erase(), finish(), and initialize().
cXMLElement* Veins::ObstacleControl::obstaclesXml protected
obstacles to add at startup
Referenced by initialize().
std::map<std::string, double> Veins::ObstacleControl::perCut protected
Referenced by addFromXml(), calculateAttenuation(), getAttenuationPerCut(), and isTypeSupported().
std::map<std::string, double> Veins::ObstacleControl::perMeter protected
Referenced by addFromXml(), calculateAttenuation(), getAttenuationPerMeter(), and isTypeSupported().
The documentation for this class was generated from the following files:
ObstacleControl.h
ObstacleControl.cc