Veins Framework: DimensionSet Class Reference
DimensionSet Class Reference
Represents a set of dimensions which is used to define over which dimensions a mapping is defined (the domain of the mapping).
#include <MappingBase.h>
Public Member Functions
DimensionSet ()
Default constructor creates an empty DimensionSet.
DimensionSet (const DimensionSet::value_type &d)
Creates a new DimensionSet with the passed Dimension as initial Dimension.
DimensionSet (const DimensionSet::value_type &d1, const DimensionSet::value_type &d2)
Creates a new DimensionSet with the passed Dimensions as initial Dimensions (convenience method)
DimensionSet (const DimensionSet::value_type &d1, const DimensionSet::value_type &d2, const DimensionSet::value_type &d3)
Creates a new DimensionSet with the passed Dimensions as initial Dimensions (convenience method)
bool isSubSet (const DimensionSet &other) const
Returns true if the passed DimensionSet is a subset of this DimensionSet.
bool isRealSubSet (const DimensionSet &other) const
Returns true if the passed DimensionSet is a real subset of this DimensionSet.
void addDimension (const DimensionSet::value_type &d)
Adds the passed dimension to the DimensionSet.
bool hasDimension (const DimensionSet::value_type &d) const
Returns true if the passed Dimension is inside this DimensionSet.
bool operator== (const DimensionSet &o)
Returns true if the dimensions of both sets are equal.
Static Public Member Functions
static const DimensionSet & timeDomain ()
Shortcut to a DimensionSet which only contains time.
static const DimensionSet & timeFreqDomain ()
Shortcut to a DimensionSet which contains time and frequency.
Detailed Description
Represents a set of dimensions which is used to define over which dimensions a mapping is defined (the domain of the mapping).
This class actually public extends from std::set<Dimension>. So any method provided by std::set can be also used.
The dimensions are stored ordered by their ids.
Note: Unlike Arguments and Mappings, a DimensionSet does not contain "time" as dimension per default. You'll have to add it like any other dimension.
Author
Karl Wessel
Constructor & Destructor Documentation
DimensionSet::DimensionSet () inline
Default constructor creates an empty DimensionSet.
 {}
DimensionSet::DimensionSet (const DimensionSet::value_type & d) inline
Creates a new DimensionSet with the passed Dimension as initial Dimension.
{
                 this->insert(d);
         }
DimensionSet::DimensionSet (const DimensionSet::value_type & d1, const DimensionSet::value_type & d2) inline
Creates a new DimensionSet with the passed Dimensions as initial Dimensions (convenience method)
{
                 this->insert(d1);
                 this->insert(d2);
         }
DimensionSet::DimensionSet (const DimensionSet::value_type & d1, const DimensionSet::value_type & d2, const DimensionSet::value_type & d3) inline
Creates a new DimensionSet with the passed Dimensions as initial Dimensions (convenience method)
{
                 this->insert(d1);
                 this->insert(d2);
                 this->insert(d3);
         }
Member Function Documentation
void DimensionSet::addDimension (const DimensionSet::value_type & d) inline
Adds the passed dimension to the DimensionSet.
{
                 this->insert(d);
         }
bool DimensionSet::hasDimension (const DimensionSet::value_type & d) const inline
Returns true if the passed Dimension is inside this DimensionSet.
Referenced by ConstMapping::ConstMapping(), MappingUtils::createMapping(), TwoRayInterferenceModel::filterSignal(), NakagamiFading::filterSignal(), SimpleObstacleShadowing::filterSignal(), SimplePathlossModel::filterSignal(), and BasePhyLayer::filterSignal().
{
                 return this->count(d) > 0;
         }
bool DimensionSet::isRealSubSet (const DimensionSet & other) const inline
Returns true if the passed DimensionSet is a real subset of this DimensionSet.
A DimensionSet is a real subset of this DimensionSet if every Dimension of the passed DimensionSet is defined in this DimensionSet and there is at least one Dimensions in this set which isn't in the other set.
{
                 if(this->size() <= other.size())
                         return false;
                 return std::includes(this->begin(), this->end(), other.begin(), other.end());
         }
bool DimensionSet::isSubSet (const DimensionSet & other) const inline
Returns true if the passed DimensionSet is a subset of this DimensionSet.
A DimensionSet is a subset of this DimensionSet if every Dimension of the passed DimensionSet is defined in this DimensionSet.
Referenced by MappingUtils::findMax(), MappingUtils::findMin(), and SimpleConstMappingIterator::SimpleConstMappingIterator().
{
                 if(this->size() < other.size())
                         return false;
                 return std::includes(this->begin(), this->end(), other.begin(), other.end());
         }
bool DimensionSet::operator== (const DimensionSet & o) inline
Returns true if the dimensions of both sets are equal.
{
                 if(size() != o.size())
                         return false;
                 return std::equal(begin(), end(), o.begin());
         }
static const DimensionSet& DimensionSet::timeDomain () inline static
Shortcut to a DimensionSet which only contains time.
Referenced by Decider80211p::calculateNoiseRSSIMapping(), BaseDecider::calculateRSSIMapping(), SNRThresholdDecider::canAnswerCSR(), Decider80211p::cca(), BaseMacLayer::createConstantMapping(), BaseMacLayer::createRectangleMapping(), Mac1609_4::createSignal(), NakagamiFading::filterSignal(), SimpleObstacleShadowing::filterSignal(), LogNormalShadowing::filterSignal(), SimplePathlossModel::filterSignal(), BasePhyLayer::filterSignal(), and BasePhyLayer::initialize().
{
                 static DimensionSet o(Dimension::time());
                 return o;
         }
static const DimensionSet& DimensionSet::timeFreqDomain () inline static
Shortcut to a DimensionSet which contains time and frequency.
Referenced by Decider80211p::calcChannelSenseRSSI(), Decider80211p::cca(), Decider80211p::checkIfSignalOk(), BaseMacLayer::createSingleFrequencyMapping(), NakagamiFading::filterSignal(), SimpleObstacleShadowing::filterSignal(), SimplePathlossModel::filterSignal(), BasePhyLayer::filterSignal(), Decider80211p::processNewSignal(), and Decider80211p::processSignalEnd().
{
                 static DimensionSet o(Dimension::time(), Dimension::frequency());
                 return o;
         }
The documentation for this class was generated from the following file:
MappingBase.h