Veins Framework: BasicSafetyMessage Class Reference
BasicSafetyMessage Class Reference
Class generated from veins/modules/messages/BasicSafetyMessage.msg:29 by nedtool.
#include <BasicSafetyMessage_m.h>
Public Member Functions
BasicSafetyMessage (const char *name=nullptr, short kind=0)
BasicSafetyMessage (const BasicSafetyMessage &other)
virtual ~BasicSafetyMessage ()
BasicSafetyMessage & operator= (const BasicSafetyMessage &other)
virtual BasicSafetyMessage * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual Coord & getSenderPos ()
virtual const Coord & getSenderPos () const
virtual void setSenderPos (const Coord &senderPos)
virtual Coord & getSenderSpeed ()
virtual const Coord & getSenderSpeed () const
virtual void setSenderSpeed (const Coord &senderSpeed)
Public Member Functions inherited from WaveShortMessage
WaveShortMessage (const char *name=nullptr, short kind=0)
WaveShortMessage (const WaveShortMessage &other)
virtual ~WaveShortMessage ()
WaveShortMessage & operator= (const WaveShortMessage &other)
virtual int getWsmVersion () const
virtual void setWsmVersion (int wsmVersion)
virtual int getSecurityType () const
virtual void setSecurityType (int securityType)
virtual int getChannelNumber () const
virtual void setChannelNumber (int channelNumber)
virtual int getDataRate () const
virtual void setDataRate (int dataRate)
virtual int getUserPriority () const
virtual void setUserPriority (int userPriority)
virtual int getPsid () const
virtual void setPsid (int psid)
virtual const char * getPsc () const
virtual void setPsc (const char *psc)
virtual int getWsmLength () const
virtual void setWsmLength (int wsmLength)
virtual const char * getWsmData () const
virtual void setWsmData (const char *wsmData)
virtual int getSenderAddress () const
virtual void setSenderAddress (int senderAddress)
virtual int getRecipientAddress () const
virtual void setRecipientAddress (int recipientAddress)
virtual int getSerial () const
virtual void setSerial (int serial)
virtual ::omnetpp::simtime_t getTimestamp () const
virtual void setTimestamp (::omnetpp::simtime_t timestamp)
Protected Member Functions
bool operator== (const BasicSafetyMessage &)
Protected Member Functions inherited from WaveShortMessage
bool operator== (const WaveShortMessage &)
Protected Attributes
Coord senderPos
Coord senderSpeed
Protected Attributes inherited from WaveShortMessage
int wsmVersion
int securityType
int channelNumber
int dataRate
int userPriority
int psid
::omnetpp::opp_string psc
int wsmLength
::omnetpp::opp_string wsmData
int senderAddress
int recipientAddress
int serial
::omnetpp::simtime_t timestamp
Private Member Functions
void copy (const BasicSafetyMessage &other)
Detailed Description
Class generated from veins/modules/messages/BasicSafetyMessage.msg:29 by nedtool.
packet BasicSafetyMessage extends WaveShortMessage
{
    Coord senderPos;
    Coord senderSpeed;
}
Constructor & Destructor Documentation
BasicSafetyMessage::BasicSafetyMessage (const char * name = nullptr, short kind = 0)
Referenced by dup().
BasicSafetyMessage::BasicSafetyMessage (const BasicSafetyMessage & other)
virtual BasicSafetyMessage::~BasicSafetyMessage () virtual
Member Function Documentation
void BasicSafetyMessage::copy (const BasicSafetyMessage & other) private
virtual BasicSafetyMessage* BasicSafetyMessage::dup () const inline override virtual
Reimplemented from WaveShortMessage.
 {return new BasicSafetyMessage(*this);}
virtual Coord& BasicSafetyMessage::getSenderPos () virtual
virtual const Coord& BasicSafetyMessage::getSenderPos () const inline virtual
Referenced by getSenderPos().
 {return const_cast<BasicSafetyMessage*>(this)->getSenderPos();}
virtual Coord& BasicSafetyMessage::getSenderSpeed () virtual
virtual const Coord& BasicSafetyMessage::getSenderSpeed () const inline virtual
Referenced by getSenderSpeed().
 {return const_cast<BasicSafetyMessage*>(this)->getSenderSpeed();}
BasicSafetyMessage& BasicSafetyMessage::operator= (const BasicSafetyMessage & other)
bool BasicSafetyMessage::operator== (const BasicSafetyMessage &) protected
virtual void BasicSafetyMessage::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from WaveShortMessage.
Referenced by doParsimPacking().
virtual void BasicSafetyMessage::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from WaveShortMessage.
Referenced by doParsimUnpacking().
virtual void BasicSafetyMessage::setSenderPos (const Coord & senderPos) virtual
virtual void BasicSafetyMessage::setSenderSpeed (const Coord & senderSpeed) virtual
Member Data Documentation
Coord BasicSafetyMessage::senderPos protected
Coord BasicSafetyMessage::senderSpeed protected
The documentation for this class was generated from the following file:
BasicSafetyMessage_m.h