Veins Framework: Veins::TraCICommandInterface Class Reference
Veins::TraCICommandInterface Class Reference
#include <TraCICommandInterface.h>
Classes
class GuiView
class Junction
class Lane
class Poi
class Polygon
class Road
class Route
class Trafficlight
class Vehicle
Public Types
enum DepartDefs { DEPART_NOW = 2, DEPART_LANE_BEST_FREE = 5, DEPART_POS_BASE = 4, DEPART_SPEED_MAX = 3 }
Public Member Functions
TraCICommandInterface (TraCIConnection &)
std::pair< uint32_t, std::string > getVersion ()
std::pair< double, double > getLonLat (const Coord &)
double getDistance (const Coord &position1, const Coord &position2, bool returnDrivingDistance)
bool addVehicle (std::string vehicleId, std::string vehicleTypeId, std::string routeId, simtime_t emitTime_st=-DEPART_NOW, double emitPosition=-DEPART_POS_BASE, double emitSpeed=-DEPART_SPEED_MAX, int8_t emitLane=-DEPART_LANE_BEST_FREE)
Vehicle vehicle (std::string nodeId)
Road road (std::string roadId)
std::list< std::string > getLaneIds ()
Lane lane (std::string laneId)
Trafficlight trafficlight (std::string trafficLightId)
std::list< std::string > getPolygonIds ()
void addPolygon (std::string polyId, std::string polyType, const TraCIColor &color, bool filled, int32_t layer, const std::list< Coord > &points)
Polygon polygon (std::string polyId)
void addPoi (std::string poiId, std::string poiType, const TraCIColor &color, int32_t layer, const Coord &pos)
Poi poi (std::string poiId)
std::list< std::string > getJunctionIds ()
Junction junction (std::string junctionId)
std::list< std::string > getRouteIds ()
Route route (std::string routeId)
std::list< std::string > getVehicleTypeIds ()
GuiView guiView (std::string viewId)
Private Member Functions
std::string genericGetString (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId)
Coord genericGetCoord (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId)
double genericGetDouble (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId)
int32_t genericGetInt (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId)
std::list< std::string > genericGetStringList (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId)
std::list< Coord > genericGetCoordList (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId)
Private Attributes
TraCIConnection & connection
Member Enumeration Documentation
enum Veins::TraCICommandInterface::DepartDefs
Enumerator
DEPART_NOW
DEPART_LANE_BEST_FREE
DEPART_POS_BASE
DEPART_SPEED_MAX
{
                         DEPART_NOW = 2,
                         DEPART_LANE_BEST_FREE = 5,
                         DEPART_POS_BASE = 4,
                         DEPART_SPEED_MAX = 3
                 };
Constructor & Destructor Documentation
Veins::TraCICommandInterface::TraCICommandInterface (TraCIConnection & c)
                                                                : connection(c)
 {
 }
Member Function Documentation
void Veins::TraCICommandInterface::addPoi (std::string poiId, std::string poiType, const TraCIColor & color, int32_t layer, const Coord & pos)
Referenced by Veins::AnnotationManager::show().
{
         TraCIBuffer p;
         TraCICoord pos = connection.omnet2traci(pos_);
         p << static_cast<uint8_t>(ADD) << poiId;
         p << static_cast<uint8_t>(TYPE_COMPOUND) << static_cast<int32_t>(4);
         p << static_cast<uint8_t>(TYPE_STRING) << poiType;
         p << static_cast<uint8_t>(TYPE_COLOR) << color.red << color.green << color.blue << color.alpha;
         p << static_cast<uint8_t>(TYPE_INTEGER) << layer;
         p << pos;
         TraCIBuffer buf = connection.query(CMD_SET_POI_VARIABLE, p);
         ASSERT(buf.eof());
 }
void Veins::TraCICommandInterface::addPolygon (std::string polyId, std::string polyType, const TraCIColor & color, bool filled, int32_t layer, const std::list< Coord > & points)
Referenced by Veins::TraCITestApp::handlePositionUpdate(), and Veins::AnnotationManager::show().
{
         TraCIBuffer p;
         p << static_cast<uint8_t>(ADD) << polyId;
         p << static_cast<uint8_t>(TYPE_COMPOUND) << static_cast<int32_t>(5);
         p << static_cast<uint8_t>(TYPE_STRING) << polyType;
         p << static_cast<uint8_t>(TYPE_COLOR) << color.red << color.green << color.blue << color.alpha;
         p << static_cast<uint8_t>(TYPE_UBYTE) << static_cast<uint8_t>(filled);
         p << static_cast<uint8_t>(TYPE_INTEGER) << layer;
         p << static_cast<uint8_t>(TYPE_POLYGON) << static_cast<uint8_t>(points.size());
         for (std::list<Coord>::const_iterator i = points.begin(); i != points.end(); ++i) {
                 const TraCICoord& pos = connection.omnet2traci(*i);
                 p << static_cast<double>(pos.x) << static_cast<double>(pos.y);
         }
         TraCIBuffer buf = connection.query(CMD_SET_POLYGON_VARIABLE, p);
         ASSERT(buf.eof());
 }
bool Veins::TraCICommandInterface::addVehicle (std::string vehicleId, std::string vehicleTypeId, std::string routeId, simtime_t emitTime_st = -DEPART_NOW, double emitPosition = -DEPART_POS_BASE, double emitSpeed = -DEPART_SPEED_MAX, int8_t emitLane = -DEPART_LANE_BEST_FREE)
Referenced by Veins::TraCITestApp::handlePositionUpdate(), and Veins::TraCIScenarioManager::insertVehicles().
{
         bool success = false;
         uint8_t variableId = ADD;
         uint8_t variableType = TYPE_COMPOUND;
         int32_t count = 6;
         int32_t emitTime = (emitTime_st < 0) ? (-1) : (floor(emitTime_st.dbl() * 1000));
         TraCIBuffer buf = connection.queryOptional(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << vehicleId << variableType << count << (uint8_t)TYPE_STRING << vehicleTypeId << (uint8_t)TYPE_STRING << routeId << (uint8_t)TYPE_INTEGER << emitTime << (uint8_t)TYPE_DOUBLE << emitPosition << (uint8_t)TYPE_DOUBLE <<emitSpeed << (uint8_t)TYPE_BYTE << emitLane, success);
         ASSERT(buf.eof());
         return success;
 }
Coord Veins::TraCICommandInterface::genericGetCoord (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId) private
{
         uint8_t resultTypeId = POSITION_2D;
         double x;
         double y;
         TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId);
         uint8_t cmdLength; buf >> cmdLength;
         if (cmdLength == 0) {
                 uint32_t cmdLengthX;
                 buf >> cmdLengthX;
         }
         uint8_t commandId_r; buf >> commandId_r;
         ASSERT(commandId_r == responseId);
         uint8_t varId; buf >> varId;
         ASSERT(varId == variableId);
         std::string objectId_r; buf >> objectId_r;
         ASSERT(objectId_r == objectId);
         uint8_t resType_r; buf >> resType_r;
         ASSERT(resType_r == resultTypeId);
         buf >> x;
         buf >> y;
         ASSERT(buf.eof());
         return connection.traci2omnet(TraCICoord(x, y));
 }
std::list< Coord > Veins::TraCICommandInterface::genericGetCoordList (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId) private
{
         uint8_t resultTypeId = TYPE_POLYGON;
         std::list<Coord> res;
         TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId);
         uint8_t cmdLength; buf >> cmdLength;
         if (cmdLength == 0) {
                 uint32_t cmdLengthX;
                 buf >> cmdLengthX;
         }
         uint8_t commandId_r; buf >> commandId_r;
         ASSERT(commandId_r == responseId);
         uint8_t varId; buf >> varId;
         ASSERT(varId == variableId);
         std::string objectId_r; buf >> objectId_r;
         ASSERT(objectId_r == objectId);
         uint8_t resType_r; buf >> resType_r;
         ASSERT(resType_r == resultTypeId);
         uint8_t count; buf >> count;
         for (uint32_t i = 0; i < count; i++) {
                 double x; buf >> x;
                 double y; buf >> y;
                 res.push_back(connection.traci2omnet(TraCICoord(x, y)));
         }
         ASSERT(buf.eof());
         return res;
 }
double Veins::TraCICommandInterface::genericGetDouble (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId) private
{
         uint8_t resultTypeId = TYPE_DOUBLE;
         double res;
         TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId);
         uint8_t cmdLength; buf >> cmdLength;
         if (cmdLength == 0) {
                 uint32_t cmdLengthX;
                 buf >> cmdLengthX;
         }
         uint8_t commandId_r; buf >> commandId_r;
         ASSERT(commandId_r == responseId);
         uint8_t varId; buf >> varId;
         ASSERT(varId == variableId);
         std::string objectId_r; buf >> objectId_r;
         ASSERT(objectId_r == objectId);
         uint8_t resType_r; buf >> resType_r;
         ASSERT(resType_r == resultTypeId);
         buf >> res;
         ASSERT(buf.eof());
         return res;
 }
int32_t Veins::TraCICommandInterface::genericGetInt (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId) private
{
         uint8_t resultTypeId = TYPE_INTEGER;
         int32_t res;
         TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId);
         uint8_t cmdLength; buf >> cmdLength;
         if (cmdLength == 0) {
                 uint32_t cmdLengthX;
                 buf >> cmdLengthX;
         }
         uint8_t commandId_r; buf >> commandId_r;
         ASSERT(commandId_r == responseId);
         uint8_t varId; buf >> varId;
         ASSERT(varId == variableId);
         std::string objectId_r; buf >> objectId_r;
         ASSERT(objectId_r == objectId);
         uint8_t resType_r; buf >> resType_r;
         ASSERT(resType_r == resultTypeId);
         buf >> res;
         ASSERT(buf.eof());
         return res;
 }
std::string Veins::TraCICommandInterface::genericGetString (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId) private
{
         uint8_t resultTypeId = TYPE_STRING;
         std::string res;
         TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId);
         uint8_t cmdLength; buf >> cmdLength;
         if (cmdLength == 0) {
                 uint32_t cmdLengthX;
                 buf >> cmdLengthX;
         }
         uint8_t commandId_r; buf >> commandId_r;
         ASSERT(commandId_r == responseId);
         uint8_t varId; buf >> varId;
         ASSERT(varId == variableId);
         std::string objectId_r; buf >> objectId_r;
         ASSERT(objectId_r == objectId);
         uint8_t resType_r; buf >> resType_r;
         ASSERT(resType_r == resultTypeId);
         buf >> res;
         ASSERT(buf.eof());
         return res;
 }
std::list< std::string > Veins::TraCICommandInterface::genericGetStringList (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId) private
Referenced by getJunctionIds(), getLaneIds(), getPolygonIds(), getRouteIds(), and getVehicleTypeIds().
{
         uint8_t resultTypeId = TYPE_STRINGLIST;
         std::list<std::string> res;
         TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId);
         uint8_t cmdLength; buf >> cmdLength;
         if (cmdLength == 0) {
                 uint32_t cmdLengthX;
                 buf >> cmdLengthX;
         }
         uint8_t commandId_r; buf >> commandId_r;
         ASSERT(commandId_r == responseId);
         uint8_t varId; buf >> varId;
         ASSERT(varId == variableId);
         std::string objectId_r; buf >> objectId_r;
         ASSERT(objectId_r == objectId);
         uint8_t resType_r; buf >> resType_r;
         ASSERT(resType_r == resultTypeId);
         uint32_t count; buf >> count;
         for (uint32_t i = 0; i < count; i++) {
                 std::string id; buf >> id;
                 res.push_back(id);
         }
         ASSERT(buf.eof());
         return res;
 }
double Veins::TraCICommandInterface::getDistance (const Coord & position1, const Coord & position2, bool returnDrivingDistance)
Referenced by Veins::TraCITestApp::handlePositionUpdate().
{
         uint8_t variable = DISTANCE_REQUEST;
         std::string simId = "sim0";
         uint8_t variableType = TYPE_COMPOUND;
         int32_t count = 3;
         uint8_t dType = static_cast<uint8_t>(returnDrivingDistance ? REQUEST_DRIVINGDIST : REQUEST_AIRDIST);
         // query road network boundaries
         TraCIBuffer buf = connection.query(CMD_GET_SIM_VARIABLE, TraCIBuffer() << variable << simId << variableType << count << connection.omnet2traci(p1) << connection.omnet2traci(p2) << dType);
         uint8_t cmdLength_resp; buf >> cmdLength_resp;
         uint8_t commandId_resp; buf >> commandId_resp; ASSERT(commandId_resp == RESPONSE_GET_SIM_VARIABLE);
         uint8_t variableId_resp; buf >> variableId_resp; ASSERT(variableId_resp == variable);
         std::string simId_resp; buf >> simId_resp; ASSERT(simId_resp == simId);
         uint8_t typeId_resp; buf >> typeId_resp; ASSERT(typeId_resp == TYPE_DOUBLE);
         double distance; buf >> distance;
         ASSERT(buf.eof());
         return distance;
 }
std::list< std::string > Veins::TraCICommandInterface::getJunctionIds ()
Referenced by Veins::TraCITestApp::handlePositionUpdate().
{
         return genericGetStringList(CMD_GET_JUNCTION_VARIABLE, "", ID_LIST, RESPONSE_GET_JUNCTION_VARIABLE);
 }
std::list< std::string > Veins::TraCICommandInterface::getLaneIds ()
Referenced by Veins::TraCITestApp::handlePositionUpdate().
{
         return genericGetStringList(CMD_GET_LANE_VARIABLE, "", ID_LIST, RESPONSE_GET_LANE_VARIABLE);
 }
std::pair< double, double > Veins::TraCICommandInterface::getLonLat (const Coord & coord)
{
         TraCIBuffer request;
         request << static_cast<uint8_t>(POSITION_CONVERSION) << std::string("sim0")
                         << static_cast<uint8_t>(TYPE_COMPOUND) << static_cast<int32_t>(2)
                         << connection.omnet2traci(coord)
                         << static_cast<uint8_t>(TYPE_UBYTE) << static_cast<uint8_t>(POSITION_LON_LAT);
         TraCIBuffer response = connection.query(CMD_GET_SIM_VARIABLE, request);
         uint8_t cmdLength; response >> cmdLength;
         if (cmdLength == 0) {
                 uint32_t cmdLengthX;
                 response >> cmdLengthX;
         }
         uint8_t responseId; response >> responseId;
         ASSERT(responseId == RESPONSE_GET_SIM_VARIABLE);
         uint8_t variable; response >> variable;
         ASSERT(variable == POSITION_CONVERSION);
         std::string id; response >> id;
         uint8_t convPosType; response >> convPosType;
         ASSERT(convPosType == POSITION_LON_LAT);
         double convPosLon; response >> convPosLon;
         double convPosLat; response >> convPosLat;
         return std::make_pair(convPosLon, convPosLat);
 }
std::list< std::string > Veins::TraCICommandInterface::getPolygonIds ()
Referenced by Veins::TraCITestApp::handlePositionUpdate(), and Veins::TraCIScenarioManager::init_traci().
{
         return genericGetStringList(CMD_GET_POLYGON_VARIABLE, "", ID_LIST, RESPONSE_GET_POLYGON_VARIABLE);
 }
std::list< std::string > Veins::TraCICommandInterface::getRouteIds ()
Referenced by Veins::TraCIScenarioManager::handleSelfMsg().
{
         return genericGetStringList(CMD_GET_ROUTE_VARIABLE, "", ID_LIST, RESPONSE_GET_ROUTE_VARIABLE);
 }
std::list< std::string > Veins::TraCICommandInterface::getVehicleTypeIds ()
Referenced by Veins::TraCIScenarioManager::handleSelfMsg().
{
         return genericGetStringList(CMD_GET_VEHICLETYPE_VARIABLE, "", ID_LIST, RESPONSE_GET_VEHICLETYPE_VARIABLE);
 }
std::pair< uint32_t, std::string > Veins::TraCICommandInterface::getVersion ()
Referenced by Veins::TraCIScenarioManagerLaunchd::init_traci(), and Veins::TraCIScenarioManager::init_traci().
{
         bool success = false;
         TraCIBuffer buf = connection.queryOptional(CMD_GETVERSION, TraCIBuffer(), success);
         if (!success) {
                 ASSERT(buf.eof());
                 return std::pair<uint32_t, std::string>(0, "(unknown)");
         }
         uint8_t cmdLength; buf >> cmdLength;
         uint8_t commandResp; buf >> commandResp;
         ASSERT(commandResp == CMD_GETVERSION);
         uint32_t apiVersion; buf >> apiVersion;
         std::string serverVersion; buf >> serverVersion;
         ASSERT(buf.eof());
         return std::pair<uint32_t, std::string>(apiVersion, serverVersion);
 }
GuiView Veins::TraCICommandInterface::guiView (std::string viewId) inline
Referenced by Veins::TraCIScreenRecorder::handleMessage().
{
                         return GuiView(this, viewId);
                 }
Junction Veins::TraCICommandInterface::junction (std::string junctionId) inline
Referenced by Veins::TraCITestApp::handlePositionUpdate().
{
                         return Junction(this, junctionId);
                 }
Lane Veins::TraCICommandInterface::lane (std::string laneId) inline
Referenced by Veins::TraCITestApp::handlePositionUpdate().
{
                         return Lane(this, laneId);
                 }
Poi Veins::TraCICommandInterface::poi (std::string poiId) inline
Referenced by Veins::AnnotationManager::hide().
{
                         return Poi(this, poiId);
                 }
Polygon Veins::TraCICommandInterface::polygon (std::string polyId) inline
Referenced by Veins::TraCITestApp::handlePositionUpdate(), Veins::AnnotationManager::hide(), and Veins::TraCIScenarioManager::init_traci().
{
                         return Polygon(this, polyId);
                 }
Road Veins::TraCICommandInterface::road (std::string roadId) inline
{
                         return Road(this, roadId);
                 }
Route Veins::TraCICommandInterface::route (std::string routeId) inline
{
                         return Route(this, routeId);
                 }
Trafficlight Veins::TraCICommandInterface::trafficlight (std::string trafficLightId) inline
Referenced by Veins::TraCITestApp::handlePositionUpdate().
{
                         return Trafficlight(this, trafficLightId);
                 }
Vehicle Veins::TraCICommandInterface::vehicle (std::string nodeId) inline
Referenced by Veins::TraCITestApp::handlePositionUpdate(), and Veins::TraCIScenarioManager::processVehicleSubscription().
{
                         return Vehicle(this, nodeId);
                 }
Member Data Documentation
TraCIConnection& Veins::TraCICommandInterface::connection private
Referenced by addPoi(), addPolygon(), addVehicle(), Veins::TraCICommandInterface::Vehicle::changeRoute(), Veins::TraCICommandInterface::Vehicle::changeVehicleRoute(), genericGetCoord(), genericGetCoordList(), genericGetDouble(), genericGetInt(), genericGetString(), genericGetStringList(), getDistance(), getLonLat(), getVersion(), Veins::TraCICommandInterface::GuiView::GuiView(), Veins::TraCICommandInterface::Junction::Junction(), Veins::TraCICommandInterface::Lane::Lane(), Veins::TraCICommandInterface::Vehicle::newRoute(), Veins::TraCICommandInterface::Poi::Poi(), Veins::TraCICommandInterface::Polygon::Polygon(), Veins::TraCICommandInterface::Polygon::remove(), Veins::TraCICommandInterface::Poi::remove(), Veins::TraCICommandInterface::Road::Road(), Veins::TraCICommandInterface::Route::Route(), Veins::TraCICommandInterface::GuiView::setBoundary(), Veins::TraCICommandInterface::Vehicle::setColor(), Veins::TraCICommandInterface::Vehicle::setParking(), Veins::TraCICommandInterface::Trafficlight::setPhaseIndex(), Veins::TraCICommandInterface::Trafficlight::setProgram(), Veins::TraCICommandInterface::GuiView::setScheme(), Veins::TraCICommandInterface::Polygon::setShape(), Veins::TraCICommandInterface::Vehicle::setSpeedMode(), Veins::TraCICommandInterface::GuiView::setZoom(), Veins::TraCICommandInterface::Vehicle::slowDown(), Veins::TraCICommandInterface::Vehicle::stopAt(), Veins::TraCICommandInterface::GuiView::takeScreenshot(), Veins::TraCICommandInterface::Trafficlight::Trafficlight(), and Veins::TraCICommandInterface::Vehicle::Vehicle().
The documentation for this class was generated from the following files:
TraCICommandInterface.h
TraCICommandInterface.cc