Veins Framework: WaveServiceAdvertisment Class Reference
WaveServiceAdvertisment Class Reference
Class generated from veins/modules/messages/WaveServiceAdvertisement.msg:29 by nedtool.
#include <WaveServiceAdvertisement_m.h>
Public Member Functions
WaveServiceAdvertisment (const char *name=nullptr, short kind=0)
WaveServiceAdvertisment (const WaveServiceAdvertisment &other)
virtual ~WaveServiceAdvertisment ()
WaveServiceAdvertisment & operator= (const WaveServiceAdvertisment &other)
virtual WaveServiceAdvertisment * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getTargetChannel () const
virtual void setTargetChannel (int targetChannel)
virtual const char * getServiceDescription () const
virtual void setServiceDescription (const char *serviceDescription)
Public Member Functions inherited from WaveShortMessage
WaveShortMessage (const char *name=nullptr, short kind=0)
WaveShortMessage (const WaveShortMessage &other)
virtual ~WaveShortMessage ()
WaveShortMessage & operator= (const WaveShortMessage &other)
virtual int getWsmVersion () const
virtual void setWsmVersion (int wsmVersion)
virtual int getSecurityType () const
virtual void setSecurityType (int securityType)
virtual int getChannelNumber () const
virtual void setChannelNumber (int channelNumber)
virtual int getDataRate () const
virtual void setDataRate (int dataRate)
virtual int getUserPriority () const
virtual void setUserPriority (int userPriority)
virtual int getPsid () const
virtual void setPsid (int psid)
virtual const char * getPsc () const
virtual void setPsc (const char *psc)
virtual int getWsmLength () const
virtual void setWsmLength (int wsmLength)
virtual const char * getWsmData () const
virtual void setWsmData (const char *wsmData)
virtual int getSenderAddress () const
virtual void setSenderAddress (int senderAddress)
virtual int getRecipientAddress () const
virtual void setRecipientAddress (int recipientAddress)
virtual int getSerial () const
virtual void setSerial (int serial)
virtual ::omnetpp::simtime_t getTimestamp () const
virtual void setTimestamp (::omnetpp::simtime_t timestamp)
Protected Member Functions
bool operator== (const WaveServiceAdvertisment &)
Protected Member Functions inherited from WaveShortMessage
bool operator== (const WaveShortMessage &)
Protected Attributes
int targetChannel
::omnetpp::opp_string serviceDescription
Protected Attributes inherited from WaveShortMessage
int wsmVersion
int securityType
int channelNumber
int dataRate
int userPriority
int psid
::omnetpp::opp_string psc
int wsmLength
::omnetpp::opp_string wsmData
int senderAddress
int recipientAddress
int serial
::omnetpp::simtime_t timestamp
Private Member Functions
void copy (const WaveServiceAdvertisment &other)
Detailed Description
Class generated from veins/modules/messages/WaveServiceAdvertisement.msg:29 by nedtool.
packet WaveServiceAdvertisment extends WaveShortMessage
{
    int targetChannel;
    string serviceDescription;
}
Constructor & Destructor Documentation
WaveServiceAdvertisment::WaveServiceAdvertisment (const char * name = nullptr, short kind = 0)
Referenced by dup().
WaveServiceAdvertisment::WaveServiceAdvertisment (const WaveServiceAdvertisment & other)
virtual WaveServiceAdvertisment::~WaveServiceAdvertisment () virtual
Member Function Documentation
void WaveServiceAdvertisment::copy (const WaveServiceAdvertisment & other) private
virtual WaveServiceAdvertisment* WaveServiceAdvertisment::dup () const inline override virtual
Reimplemented from WaveShortMessage.
 {return new WaveServiceAdvertisment(*this);}
virtual const char* WaveServiceAdvertisment::getServiceDescription () const virtual
virtual int WaveServiceAdvertisment::getTargetChannel () const virtual
Referenced by TraCIDemoRSU11p::onWSA(), and TraCIDemo11p::onWSA().
WaveServiceAdvertisment& WaveServiceAdvertisment::operator= (const WaveServiceAdvertisment & other)
bool WaveServiceAdvertisment::operator== (const WaveServiceAdvertisment &) protected
virtual void WaveServiceAdvertisment::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from WaveShortMessage.
Referenced by doParsimPacking().
virtual void WaveServiceAdvertisment::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from WaveShortMessage.
Referenced by doParsimUnpacking().
virtual void WaveServiceAdvertisment::setServiceDescription (const char * serviceDescription) virtual
virtual void WaveServiceAdvertisment::setTargetChannel (int targetChannel) virtual
Member Data Documentation
::omnetpp::opp_string WaveServiceAdvertisment::serviceDescription protected
int WaveServiceAdvertisment::targetChannel protected
The documentation for this class was generated from the following file:
WaveServiceAdvertisement_m.h