Veins Framework: LAddress Class Reference
LAddress Class Reference
Layer address handling helper function.
#include <SimpleAddress.h>
Public Types
typedef long L2Type
Type definition for a L2 (MAC) address.
typedef long L3Type
Type definition for a L3 (Network) address.
Static Public Member Functions
static const L2Type & L2BROADCAST ()
Broadcast address for L2 addresses.
static const L2Type & L2NULL ()
NULL address for L2 addresses.
static const L3Type & L3BROADCAST ()
Broadcast address for L3 addresses.
static const L3Type & L3NULL ()
NULL address for L3 addresses.
static bool isL2Broadcast (const L2Type &pSrcAddr)
Test if a L2 address (pSrcAddr) is a broadcast address.
static bool isL3Broadcast (const L3Type &pSrcAddr)
Test if a L3 address (pSrcAddr) is a broadcast address.
Detailed Description
Layer address handling helper function.
This class helps to make the layer addressing more generic. The type definition for L2, and L3 addresses should be used for address definitions to simplify the switching to other types.
Both types (LAddress::L2Type, LAddress::L3Type) will be used as keys in in STL containers.
Member Typedef Documentation
typedef long LAddress::L2Type
Type definition for a L2 (MAC) address.
The type should support initialization with long/string values and casting to long/double. The type should be also support the ==,<, and > operators.
typedef long LAddress::L3Type
Type definition for a L3 (Network) address.
The type should support initialization with long values and casting to long/double. The type should be also support the ==,<, and > operators.
Member Function Documentation
static bool LAddress::isL2Broadcast (const L2Type & pSrcAddr) inline static
Test if a L2 address (pSrcAddr) is a broadcast address.
Parameters
pSrcAddr The L2 address which should be tested.
Returns
True if pSrcAddr is a braodcast address.
Referenced by BaseMacLayer::handleLowerMsg().
{
         return pSrcAddr == L2BROADCAST();
     }
static bool LAddress::isL3Broadcast (const L3Type & pSrcAddr) inline static
Test if a L3 address (pSrcAddr) is a broadcast address.
Parameters
pSrcAddr The L3 address which should be tested.
Returns
True if pSrcAddr is a braodcast address.
{
         return pSrcAddr == L3BROADCAST();
     }
static const L2Type& LAddress::L2BROADCAST () inline static
Broadcast address for L2 addresses.
Referenced by Mac1609_4::handleLowerMsg(), and Mac1609_4::handleSelfMsg().
{
         static L2Type o(-1);
         return o;
     }
static const L2Type& LAddress::L2NULL () inline static
NULL address for L2 addresses.
Referenced by MacToNetwControlInfo::getAddressFromControlInfo(), and BaseMacLayer::initialize().
{
         static L2Type o(0);
         return o;
     }
static const L3Type& LAddress::L3BROADCAST () inline static
Broadcast address for L3 addresses.
{
         static L3Type o(-1);
         return o;
     }
static const L3Type& LAddress::L3NULL () inline static
NULL address for L3 addresses.
{
         static L3Type o(0);
         return o;
     }
The documentation for this class was generated from the following file:
SimpleAddress.h