Veins Framework: Veins::AirFrame Class Reference
Veins::AirFrame Class Reference
Class generated from veins/base/messages/AirFrame.msg:35 by nedtool.
#include <AirFrame_m.h>
Public Member Functions
AirFrame (const char *name=nullptr, short kind=0)
AirFrame (const AirFrame &other)
virtual ~AirFrame ()
AirFrame & operator= (const AirFrame &other)
virtual AirFrame * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual Signal & getSignal ()
virtual const Signal & getSignal () const
virtual void setSignal (const Signal &signal)
virtual POA & getPoa ()
virtual const POA & getPoa () const
virtual void setPoa (const POA &poa)
virtual ::omnetpp::simtime_t getDuration () const
virtual void setDuration (::omnetpp::simtime_t duration)
virtual int getState () const
virtual void setState (int state)
virtual int getType () const
virtual void setType (int type)
virtual long getId () const
virtual void setId (long id)
virtual int getProtocolId () const
virtual void setProtocolId (int protocolId)
virtual int getChannel () const
virtual void setChannel (int channel)
Protected Member Functions
bool operator== (const AirFrame &)
Protected Attributes
Signal signal
POA poa
::omnetpp::simtime_t duration
int state
int type
long id
int protocolId
int channel
Private Member Functions
void copy (const AirFrame &other)
Detailed Description
Class generated from veins/base/messages/AirFrame.msg:35 by nedtool.
packet AirFrame
{
    Signal signal;              // Contains the physical data of this AirFrame
    POA poa;                    // contains a POA object with the position, orientation and antenna (pointer)
                                                // of the sender
    simtime_t duration; // time the AirFrames takes to be transmited (without propagation delay)
    int state = 1;              // state of the AirFrames, used by the physical layer
                                                // as state machine for delay and transmission duration
                                                // simulation
    int type = 0;               // If type isn't null then this is a control-AirFrame
                                                // and type specifies the control type.
    long id;                    // Unique ID of the AirFrame used as identifier for
                                                        // related control-AirFrames
    int protocolId;             //the id of the phy protocol of this airframe
    int channel;        //the channel of the radio used for this transmission
}
Constructor & Destructor Documentation
Veins::AirFrame::AirFrame (const char * name = nullptr, short kind = 0)
Referenced by dup().
Veins::AirFrame::AirFrame (const AirFrame & other)
virtual Veins::AirFrame::~AirFrame () virtual
Member Function Documentation
void Veins::AirFrame::copy (const AirFrame & other) private
virtual AirFrame* Veins::AirFrame::dup () const inline override virtual
Reimplemented in AirFrame11p.
 {return new AirFrame(*this);}
virtual int Veins::AirFrame::getChannel () const virtual
virtual ::omnetpp::simtime_t Veins::AirFrame::getDuration () const
Referenced by ChannelInfo::addAirFrame(), ChannelInfo::checkAndCleanInterval(), BasePhyLayer::handleAirFrameReceiving(), BasePhyLayer::handleAirFrameStartReceive(), BasePhyLayer::handleUpperMessage(), and ChannelInfo::removeAirFrame().
virtual long Veins::AirFrame::getId () const virtual
Referenced by BaseDecider::calculateRSSIMapping(), BasePhyLayer::handleAirFrameEndReceive(), BasePhyLayer::handleAirFrameReceiving(), Decider80211p::processNewSignal(), BaseDecider::processUnknownSignal(), and BasePhyLayer::sendUp().
virtual POA& Veins::AirFrame::getPoa () virtual
Referenced by BasePhyLayer::filterSignal().
virtual const POA& Veins::AirFrame::getPoa () const inline virtual
Referenced by getPoa().
 {return const_cast<AirFrame*>(this)->getPoa();}
virtual int Veins::AirFrame::getProtocolId () const virtual
Referenced by BasePhyLayer::handleAirFrameStartReceive().
virtual Signal& Veins::AirFrame::getSignal () virtual
Referenced by Decider80211p::calculateNoiseRSSIMapping(), BaseDecider::calculateRSSIMapping(), Decider80211p::calculateSinrAndSnrMapping(), BaseDecider::calculateSnrMapping(), Decider80211p::checkIfSignalOk(), PERModel::filterSignal(), TwoRayInterferenceModel::filterSignal(), NakagamiFading::filterSignal(), SimpleObstacleShadowing::filterSignal(), LogNormalShadowing::filterSignal(), BreakpointPathlossModel::filterSignal(), JakesFading::filterSignal(), SimplePathlossModel::filterSignal(), RadioStateAnalogueModel::filterSignal(), BasePhyLayer::filterSignal(), BasePhyLayer::handleAirFrameReceiving(), BasePhyLayer::handleAirFrameStartReceive(), SNRThresholdDecider::processNewSignal(), Decider80211p::processNewSignal(), BaseDecider::processNewSignal(), SNRThresholdDecider::processSignalEnd(), and Decider80211p::processSignalEnd().
virtual const Signal& Veins::AirFrame::getSignal () const inline virtual
Referenced by getSignal().
 {return const_cast<AirFrame*>(this)->getSignal();}
virtual int Veins::AirFrame::getState () const virtual
Referenced by BasePhyLayer::handleAirFrame().
virtual int Veins::AirFrame::getType () const virtual
AirFrame& Veins::AirFrame::operator= (const AirFrame & other)
bool Veins::AirFrame::operator== (const AirFrame &) protected
virtual void Veins::AirFrame::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in AirFrame11p.
Referenced by Veins::doParsimPacking().
virtual void Veins::AirFrame::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in AirFrame11p.
Referenced by Veins::doParsimUnpacking().
virtual void Veins::AirFrame::setChannel (int channel) virtual
Referenced by PhyLayer80211p::encapsMsg(), and BasePhyLayer::encapsMsg().
virtual void Veins::AirFrame::setDuration (::omnetpp::simtime_t duration) virtual
Referenced by PhyLayer80211p::encapsMsg(), and BasePhyLayer::encapsMsg().
virtual void Veins::AirFrame::setId (long id) virtual
Referenced by PhyLayer80211p::encapsMsg(), and BasePhyLayer::encapsMsg().
virtual void Veins::AirFrame::setPoa (const POA & poa) virtual
Referenced by BasePhyLayer::handleUpperMessage().
virtual void Veins::AirFrame::setProtocolId (int protocolId) virtual
Referenced by PhyLayer80211p::encapsMsg(), and BasePhyLayer::encapsMsg().
virtual void Veins::AirFrame::setSignal (const Signal & signal) virtual
Referenced by PhyLayer80211p::encapsMsg(), and BasePhyLayer::encapsMsg().
virtual void Veins::AirFrame::setState (int state) virtual
Referenced by BasePhyLayer::handleAirFrameReceiving(), and BasePhyLayer::handleAirFrameStartReceive().
virtual void Veins::AirFrame::setType (int type) virtual
Member Data Documentation
int Veins::AirFrame::channel protected
::omnetpp::simtime_t Veins::AirFrame::duration protected
long Veins::AirFrame::id protected
POA Veins::AirFrame::poa protected
int Veins::AirFrame::protocolId protected
Signal Veins::AirFrame::signal protected
int Veins::AirFrame::state protected
int Veins::AirFrame::type protected
The documentation for this class was generated from the following file:
AirFrame_m.h