Veins Framework: Dimension Class Reference
Dimension Class Reference
Specifies a dimension for mappings (like time, frequency, etc.)
#include <MappingBase.h>
Public Types
typedef std::map< std::string,
int > DimensionIDMap
Type for map from dimension name to ID.
typedef DimensionIDMap::key_type DimensionNameType
typedef DimensionIDMap::mapped_type DimensionIdType
Public Member Functions
Dimension ()
Dimension (const DimensionNameType &name)
Creates a new dimension instance representing the dimension with the passed name.
bool operator== (const Dimension &other) const
Returns true if the ids of the two dimensions are equal.
bool operator< (const Dimension &other) const
Returns true if the id of the other dimension is greater then the id of this dimension.
bool operator<= (const Dimension &other) const
Sorting operator by dimension ID.
bool operator> (const Dimension &other) const
Sorting operator by dimension ID.
bool operator>= (const Dimension &other) const
Sorting operator by dimension ID.
bool operator!= (const Dimension &other) const
Sorting operator by dimension ID.
DimensionNameType getName () const
Returns the name of this dimension.
DimensionIdType getID () const
Returns the unique id of the dimension this instance represents.
Static Public Member Functions
static const Dimension & time ()
Shortcut to the time Dimension, same as 'Dimension("time")', but spares the parsing of a string.
static const Dimension & frequency ()
Shortcut to the frequency Dimension, same as 'Dimension("frequency")', but spares the parsing of a string.
Protected Types
typedef std::map
< DimensionIdType,
DimensionNameType > DimensionNameMap
Type for map from ID to dimension name.
Static Protected Member Functions
static DimensionIDMap & dimensionIDs ()
stores the registered dimensions ids.
static DimensionNameMap & dimensionNames ()
ConstMapping from id to name of registered dimensions.
static DimensionIdType & nextFreeID ()
Stores the next free ID for a new dimension.
static int getDimensionID (const DimensionNameType &name)
Returns an instance of dimension which represents the dimension with the passed name.
Protected Attributes
DimensionIdType id
The unique id of the dimension this instance represents.
Friends
std::ostream & operator<< (std::ostream &out, const Dimension &d)
Output operator for a dimension.
Detailed Description
Specifies a dimension for mappings (like time, frequency, etc.)
The dimension is represented external by a string (like "time") and internally by an unique ID.
Note: Since the ID for a Dimensions is set the first time an instance of this dimensions is created and the id is used to provide a defined ordering of the Dimensions it DOES matter which dimensions are instantiated the first time. Only the time dimension will always have zero as unique id.
Author
Karl Wessel
Member Typedef Documentation
typedef std::map<std::string, int> Dimension::DimensionIDMap
Type for map from dimension name to ID.
typedef DimensionIDMap::mapped_type Dimension::DimensionIdType
typedef std::map< DimensionIdType , DimensionNameType> Dimension::DimensionNameMap protected
Type for map from ID to dimension name.
typedef DimensionIDMap::key_type Dimension::DimensionNameType
Constructor & Destructor Documentation
Dimension::Dimension () inline
                    :
                 id(0)
         {}
Dimension::Dimension (const DimensionNameType & name)
Creates a new dimension instance representing the dimension with the passed name.
         : id(getDimensionID(name))
 {}
Member Function Documentation
Dimension::DimensionIDMap & Dimension::dimensionIDs () static protected
stores the registered dimensions ids.
Uses "construct-on-first-use" idiom to ensure correct initialization of static members.
Referenced by getDimensionID().
{
         //use "construct-on-first-use" idiom to ensure correct order of
         //static initialization
         static DimensionIDMap* dimIDs = new DimensionIDMap();
         return *dimIDs;
 }
Dimension::DimensionNameMap & Dimension::dimensionNames () static protected
ConstMapping from id to name of registered dimensions.
Uses "construct-on-first-use" idiom to ensure correct initialization of static members.
Referenced by getDimensionID(), and getName().
{
         //use "construct-on-first-use" idiom to ensure correct order of
         //static initialization
         static DimensionNameMap* names = new DimensionNameMap();
         return *names;
 }
static const Dimension& Dimension::frequency () inline static
Shortcut to the frequency Dimension, same as 'Dimension("frequency")', but spares the parsing of a string.
Referenced by Decider80211p::calcChannelSenseRSSI(), Decider80211p::cca(), Decider80211p::checkIfSignalOk(), BaseMacLayer::createSingleFrequencyMapping(), TwoRayInterferenceModel::filterSignal(), NakagamiFading::filterSignal(), SimpleObstacleShadowing::filterSignal(), SimplePathlossModel::filterSignal(), BasePhyLayer::filterSignal(), SimplePathlossConstMapping::getValue(), TwoRayInterferenceModel::Mapping::getValue(), Decider80211p::processNewSignal(), Decider80211p::processSignalEnd(), and DimensionSet::timeFreqDomain().
{
                 static Dimension o("frequency");
                 return o;
         }
Dimension::DimensionIdType Dimension::getDimensionID (const DimensionNameType & name) static protected
Returns an instance of dimension which represents the dimension with the passed name.
 {
         //get static members one time during initialization
         static DimensionIDMap&   dimensionIDs   = Dimension::dimensionIDs();
         static DimensionIdType&  nextFreeID     = Dimension::nextFreeID();
         static DimensionNameMap& dimensionNames = Dimension::dimensionNames();
         DimensionIDMap::iterator it             = dimensionIDs.lower_bound(name);
         if(it == dimensionIDs.end() || dimensionIDs.key_comp()(name, it->first)) {
                 DimensionIdType newID = 0;
                 //time gets its own id to make sure it has the smallest
                 if( dimensionIDs.key_comp()(name, "time") || dimensionIDs.key_comp()("time", name) )
                         newID = nextFreeID++;
                 it = dimensionIDs.insert(it, DimensionIDMap::value_type(name, newID));
                 dimensionNames[newID] = name;
         }
         return it->second;
 }
DimensionIdType Dimension::getID () const inline
Returns the unique id of the dimension this instance represents.
The id is used to uniquely identify dimensions as well as to provide a sorting of dimensions. Note: The "time"-dimension will always have the ID zero.
 { return id; }
DimensionNameType Dimension::getName () const inline
Returns the name of this dimension.
{
                 static DimensionNameMap& dimensionNames = Dimension::dimensionNames();
                 return dimensionNames.find(id)->second;
         }
Dimension::DimensionIdType & Dimension::nextFreeID () static protected
Stores the next free ID for a new dimension.
Uses "construct-on-first-use" idiom to ensure correct initialization of static members.
Referenced by getDimensionID().
{
         static Dimension::DimensionIdType* nextID = new Dimension::DimensionIdType(1);
         return *nextID;
 }
bool Dimension::operator!= (const Dimension & other) const inline
Sorting operator by dimension ID.
 { return id != other.id; }
bool Dimension::operator< (const Dimension & other) const inline
Returns true if the id of the other dimension is greater then the id of this dimension.
This is needed to be able to use Dimension as a key in std::map.
 { return id  < other.id; }
bool Dimension::operator<= (const Dimension & other) const inline
Sorting operator by dimension ID.
 { return id <= other.id; }
bool Dimension::operator== (const Dimension & other) const inline
Returns true if the ids of the two dimensions are equal.
 { return id == other.id; }
bool Dimension::operator> (const Dimension & other) const inline
Sorting operator by dimension ID.
 { return id  > other.id; }
bool Dimension::operator>= (const Dimension & other) const inline
Sorting operator by dimension ID.
 { return id >= other.id; }
static const Dimension& Dimension::time () inline static
Shortcut to the time Dimension, same as 'Dimension("time")', but spares the parsing of a string.
Referenced by Argument::Argument(), Argument::compare(), ConstMapping::ConstMapping(), MultiDimMapping< Linear >::copySubMappings(), SimpleConstMapping::createKeyEntries(), MappingUtils::createMapping(), MultiDimMapping< Linear >::createSubSignal(), FilledUpMapping::createSubSignal(), Argument::find(), Argument::getDimensions(), SimpleConstMapping::initializeArguments(), Argument::lower_bound(), ConstMapping::print(), Argument::setArgValue(), DimensionSet::timeDomain(), and DimensionSet::timeFreqDomain().
{
                 static Dimension o("time");
                 return o;
         }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const Dimension & d) friend
Output operator for a dimension.
{
         return (out << d.getName() << "(" << d.id << ")");
     }
Member Data Documentation
DimensionIdType Dimension::id protected
The unique id of the dimension this instance represents.
Referenced by operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
The documentation for this class was generated from the following files:
MappingBase.h
MappingBase.cc