Veins Framework: AirFrame11p Class Reference
AirFrame11p Class Reference
Class generated from veins/modules/messages/AirFrame11p.msg:25 by nedtool.
#include <AirFrame11p_m.h>
Public Member Functions
AirFrame11p (const char *name=nullptr, short kind=0)
AirFrame11p (const AirFrame11p &other)
virtual ~AirFrame11p ()
AirFrame11p & operator= (const AirFrame11p &other)
virtual AirFrame11p * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual bool getUnderSensitivity () const
virtual void setUnderSensitivity (bool underSensitivity)
virtual bool getWasTransmitting () const
virtual void setWasTransmitting (bool wasTransmitting)
Public Member Functions inherited from Veins::AirFrame
AirFrame (const char *name=nullptr, short kind=0)
AirFrame (const AirFrame &other)
virtual ~AirFrame ()
AirFrame & operator= (const AirFrame &other)
virtual Signal & getSignal ()
virtual const Signal & getSignal () const
virtual void setSignal (const Signal &signal)
virtual POA & getPoa ()
virtual const POA & getPoa () const
virtual void setPoa (const POA &poa)
virtual ::omnetpp::simtime_t getDuration () const
virtual void setDuration (::omnetpp::simtime_t duration)
virtual int getState () const
virtual void setState (int state)
virtual int getType () const
virtual void setType (int type)
virtual long getId () const
virtual void setId (long id)
virtual int getProtocolId () const
virtual void setProtocolId (int protocolId)
virtual int getChannel () const
virtual void setChannel (int channel)
Protected Member Functions
bool operator== (const AirFrame11p &)
Protected Member Functions inherited from Veins::AirFrame
bool operator== (const AirFrame &)
Protected Attributes
bool underSensitivity
bool wasTransmitting
Protected Attributes inherited from Veins::AirFrame
Signal signal
POA poa
::omnetpp::simtime_t duration
int state
int type
long id
int protocolId
int channel
Private Member Functions
void copy (const AirFrame11p &other)
Detailed Description
Class generated from veins/modules/messages/AirFrame11p.msg:25 by nedtool.
//
// Extension of base AirFrame message to have the underSensitivity field
//
message AirFrame11p extends AirFrame
{
    bool underSensitivity = false;
    bool wasTransmitting = false;
}
Constructor & Destructor Documentation
AirFrame11p::AirFrame11p (const char * name = nullptr, short kind = 0)
Referenced by dup().
AirFrame11p::AirFrame11p (const AirFrame11p & other)
virtual AirFrame11p::~AirFrame11p () virtual
Member Function Documentation
void AirFrame11p::copy (const AirFrame11p & other) private
virtual AirFrame11p* AirFrame11p::dup () const inline override virtual
Reimplemented from Veins::AirFrame.
 {return new AirFrame11p(*this);}
virtual bool AirFrame11p::getUnderSensitivity () const virtual
Referenced by Decider80211p::processSignalEnd().
virtual bool AirFrame11p::getWasTransmitting () const virtual
Referenced by Decider80211p::processSignalEnd().
AirFrame11p& AirFrame11p::operator= (const AirFrame11p & other)
bool AirFrame11p::operator== (const AirFrame11p &) protected
virtual void AirFrame11p::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from Veins::AirFrame.
Referenced by doParsimPacking().
virtual void AirFrame11p::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from Veins::AirFrame.
Referenced by doParsimUnpacking().
virtual void AirFrame11p::setUnderSensitivity (bool underSensitivity) virtual
Referenced by Decider80211p::processNewSignal().
virtual void AirFrame11p::setWasTransmitting (bool wasTransmitting) virtual
Referenced by Decider80211p::processNewSignal(), and Decider80211p::switchToTx().
Member Data Documentation
bool AirFrame11p::underSensitivity protected
bool AirFrame11p::wasTransmitting protected
The documentation for this class was generated from the following file:
AirFrame11p_m.h