Veins Framework: BasePhyLayer Class Reference
BasePhyLayer Class Reference
The BasePhyLayer represents the physical layer of a nic.
#include <BasePhyLayer.h>
Public Member Functions
BasePhyLayer ()
virtual ~BasePhyLayer ()
Free the pointer to the decider and the AnalogueModels and the Radio.
virtual void finish ()
Only calls the deciders finish method.
virtual cObject *const setUpControlInfo (cMessage *const pMsg, DeciderResult *const pDeciderResult)
Attaches a "control info" (PhyToMac) structure (object) to the message pMsg.
MacToPhyInterface implementation
These methods implement the MacToPhyInterface.
virtual int getRadioState ()
Returns the current state the radio is in.
virtual simtime_t setRadioState (int rs)
Tells the BasePhyLayer to switch to the specified radio state.
virtual ChannelState getChannelState ()
Returns the current state of the channel.
virtual int getPhyHeaderLength ()
Returns the length of the phy header in bits.
virtual void setCurrentRadioChannel (int newRadioChannel)
Sets the channel currently used by the radio.
virtual int getCurrentRadioChannel ()
Returns the channel currently used by the radio.
virtual int getNbRadioChannels ()
Returns the number of channels available on this radio.
DeciderToPhyInterface implementation
These methods implement the DeciderToPhyInterface.
virtual void getChannelInfo (simtime_t_cref from, simtime_t_cref to, AirFrameVector &out)
Fills the passed AirFrameVector with all AirFrames that intersect with the time interval [from, to].
virtual ConstMapping * getThermalNoise (simtime_t_cref from, simtime_t_cref to)
Returns a Mapping which defines the thermal noise in the passed time frame (in mW).
virtual void sendControlMsgToMac (cMessage *msg)
Called by the Decider to send a control message to the MACLayer.
virtual void sendUp (AirFrame *packet, DeciderResult *result)
Called to send an AirFrame with DeciderResult to the MACLayer.
virtual simtime_t getSimTime ()
Returns the current simulation time.
virtual void cancelScheduledMessage (cMessage *msg)
Tells the PhyLayer to cancel a scheduled message (AirFrame or ControlMessage).
virtual void rescheduleMessage (cMessage *msg, simtime_t_cref t)
Tells the PhyLayer to reschedule a message (AirFrame or ControlMessage).
virtual void drawCurrent (double amount, int activity)
Does nothing.
virtual BaseWorldUtility * getWorldUtility ()
Returns a pointer to the simulations world-utility-module.
void recordScalar (const char *name, double value, const char *unit=NULL)
Records a double into the scalar result file.
Public Member Functions inherited from Veins::ChannelAccess
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details)
Called by the signalling mechanism to inform of changes.
virtual ChannelMobilityPtrType getMobilityModule ()
Returns the host's mobility module.
Public Member Functions inherited from Veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from BaseModule
BaseModule ()
BaseModule (unsigned stacksize)
virtual int numInitStages () const
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Public Member Functions inherited from DeciderToPhyInterface
virtual ~DeciderToPhyInterface ()
Public Member Functions inherited from MacToPhyInterface
virtual ~MacToPhyInterface ()
Protected Types
enum ProtocolIds { GENERIC = 0 }
enum AirFrameStates { START_RECEIVE = 1, RECEIVING, END_RECEIVE }
The states of the receiving process for AirFrames.
typedef std::vector
< AnalogueModel * > AnalogueModelList
Used to store the AnalogueModels to be used as filters.
typedef std::map< std::string,
cMsgPar > ParameterMap
Used at initialisation to pass the parameters to the AnalogueModel and Decider.
Protected Types inherited from AccessModuleWrap< T >
typedef T wrapType
Protected Member Functions
template<class T >
T readPar (const char *parName, const T defaultValue)
Reads and returns the parameter with the passed name.
virtual void initialize (int stage)
OMNeT++ initialization function.
virtual void handleMessage (cMessage *msg)
OMNeT++ handle message function.
virtual Radio * initializeRadio ()
Initializes and returns the radio class to use.
virtual AnalogueModel * getAnalogueModelFromName (std::string name, ParameterMap &params)
Creates and returns an instance of the AnalogueModel with the specified name.
virtual Decider * getDeciderFromName (std::string name, ParameterMap &params)
Creates and returns an instance of the Decider with the specified name.
virtual std::shared_ptr< Antenna > getAntennaFromName (std::string name, ParameterMap &params)
Creates and returns an instance of the Antenna with the specified name as a shared pointer.
virtual std::shared_ptr< Antenna > initializeSampledAntenna1D (ParameterMap &params)
Creates and returns an instance of the SampledAntenna1D class as a shared pointer.
virtual AirFrame * encapsMsg (cPacket *msg)
This function encapsulates messages from the upper layer into an AirFrame and sets all necessary attributes.
virtual void filterSignal (AirFrame *frame)
Filters the passed AirFrame's Signal by every registered AnalogueModel.
virtual void finishRadioSwitching ()
Called the moment the simulated switching process of the Radio is finished.
virtual int myProtocolId ()
Returns the identifier of the protocol this phy uses to send messages.
virtual bool isKnownProtocolId (int id)
Returns true if the protocol with the passed identifier is decodeable by the decider.
Handle Messages
virtual void handleAirFrame (AirFrame *frame)
Handles messages received from the channel (probably AirFrames).
virtual void handleUpperMessage (cMessage *msg)
Handles messages received from the upper layer through the data gate.
virtual void handleUpperControlMessage (cMessage *msg)
Handles messages received from the upper layer through the control gate.
virtual void handleSelfMessage (cMessage *msg)
Handles self scheduled messages.
virtual void handleChannelSenseRequest (cMessage *msg)
Handles reception of a ChannelSenseRequest by forwarding it to the decider and scheduling it to the point in time returned by the decider.
void handleAirFrameFirstReceive (AirFrame *msg)
Handles incoming AirFrames with the state FIRST_RECEIVE.
virtual void handleAirFrameStartReceive (AirFrame *msg)
Handles incoming AirFrames with the state START_RECEIVE.
virtual void handleAirFrameReceiving (AirFrame *msg)
Handles incoming AirFrames with the state RECEIVING.
virtual void handleAirFrameEndReceive (AirFrame *msg)
Handles incoming AirFrames with the state END_RECEIVE.
Send Messages
void sendControlMessageUp (cMessage *msg)
Sends the passed control message to the upper layer.
void sendMacPktUp (cMessage *pkt)
Sends the passed MacPkt to the upper layer.
void sendMessageDown (AirFrame *pkt)
Sends the passed AirFrame to the channel.
void sendSelfMessage (cMessage *msg, simtime_t_cref time)
Schedule self message to passed point in time.
Protected Member Functions inherited from Veins::ChannelAccess
simtime_t calculatePropagationDelay (const NicEntry *nic)
Calculates the propagation delay to the passed receiving nic.
void sendToChannel (cPacket *msg)
Sends a message to all nics connected to this one.
Protected Member Functions inherited from Veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
virtual void finish (cComponent *component, simsignal_t signalID)
Protected Member Functions inherited from AccessModuleWrap< T >
AccessModuleWrap ()
T *const get (cModule *const from=NULL)
Static Protected Member Functions
static short airFramePriority ()
Defines the scheduling priority of AirFrames.
Protected Attributes
int protocolId
ConstantSimpleConstMapping * thermalNoise
Defines the strength of the thermal noise.
double sensitivity
The sensitivity describes the minimum strength a signal must have to be received.
bool recordStats
Stores if tracking of statistics (esp.
ChannelInfo channelInfo
Channel info keeps track of received AirFrames and provides information about currently active AirFrames at the channel.
Radio * radio
The state machine storing the current radio state (TX, RX, SLEEP).
std::shared_ptr< Antenna > antenna
Shared pointer to the Antenna used for this node.
Decider * decider
Pointer to the decider module.
AnalogueModelList analogueModels
List of the analogue models to use.
int upperLayerIn
The id of the in-data gate from the Mac layer.
int upperLayerOut
The id of the out-data gate to the Mac layer.
int upperControlOut
The id of the out-control gate to the Mac layer.
int upperControlIn
The id of the in-control gate from the Mac layer.
cMessage * radioSwitchingOverTimer
Self message scheduled to the point in time when the switching process of the radio is over.
cMessage * txOverTimer
Self message scheduled to the point in time when the transmission of an AirFrame is over.
int headerLength
Stores the length of the phy header in bits.
BaseWorldUtility * world
Pointer to the World Utility, to obtain some global information.
Protected Attributes inherited from Veins::ChannelAccess
bool useSendDirect
use sendDirect or not?
BaseConnectionManager * cc
Pointer to the PropagationModel module.
bool coreDebug
debug this core module?
bool usePropagationDelay
Defines if the physical layer should simulate propagation delay.
bool isRegistered
Is this module already registered with ConnectionManager?
BaseWorldUtility * world
Pointer to the World Utility, to obtain some global information.
Protected Attributes inherited from Veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from BaseModule
bool debug
Debug switch for all other modules.
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Private Member Functions
void getParametersFromXML (cXMLElement *xmlData, ParameterMap &outputMap)
Utility function.
void initializeAnalogueModels (cXMLElement *xmlConfig)
Initializes the AnalogueModels with the data from the passed XML-config data.
void initializeDecider (cXMLElement *xmlConfig)
Initializes the Decider with the data from the passed XML-config data.
void initializeAntenna (cXMLElement *xmlConfig)
Initializes the Antenna with the data from the passed XML-config data.
Additional Inherited Members
Public Types inherited from DeciderToPhyInterface
typedef std::list< AirFrame * > AirFrameVector
Type for container of AirFrames.
Public Types inherited from MacToPhyInterface
enum BasePhyMessageKinds {
TX_OVER = 22000, RADIO_SWITCHING_OVER, CHANNEL_SENSE_REQUEST, AIR_FRAME,
LAST_BASE_PHY_KIND
}
Message kinds used by every phy layer.
Static Public Member Functions inherited from Veins::ChannelAccess
static BaseConnectionManager * getConnectionManager (cModule *nic)
Returns a pointer to the ConnectionManager responsible for the passed NIC module.
Static Protected Attributes inherited from Veins::ChannelAccess
static const simsignalwrap_t mobilityStateChangedSignal = simsignalwrap_t(MIXIM_SIGNAL_MOBILITY_CHANGE_NAME)
A signal used to subscribe to mobility state changes.
Static Protected Attributes inherited from BaseModule
static const simsignalwrap_t catHostStateSignal = simsignalwrap_t(MIXIM_SIGNAL_HOSTSTATE_NAME)
Stores the category of the HostState.
Detailed Description
The BasePhyLayer represents the physical layer of a nic.
The BasePhyLayer is directly connected to the mac layer via OMNeT channels and is able to send messages to other physical layers through sub-classing from ChannelAcces.
The BasePhyLayer encapsulates three sub modules. The AnalogueModels, which are responsible for simulating the attenuation of received signals and the Decider which provides the main functionality of the physical layer like signal classification (noise or not noise) and demodulation (calculating transmission errors). Furthermore, the Antenna used for gain calculation is managed by the BasePhyLayer.
The BasePhyLayer itself is responsible for the OMNeT depended parts of the physical layer which are the following:
Module initialization:
read ned-parameters and initialize module, Decider, AnalogueModels and Antenna.
Message handling:
receive messages from mac layer and hand them to the Decider or directly send them to the channel
receive AirFrames from the channel, hand them to the AnalogueModels for filtering, simulate delay and transmission duration, hand it to the Decider for evaluation and send received packets to the mac layer
keep track of currently active AirFrames on the channel (see ChannelInfo)
The actual evaluation of incoming signals is done by the Decider.
base class ChannelAccess:
provides access to the channel via the ConnectionManager
base class DeciderToPhyInterface:
interface for the Decider
base class MacToPhyInterface:
interface for the Mac
Member Typedef Documentation
typedef std::vector<AnalogueModel*> BasePhyLayer::AnalogueModelList protected
Used to store the AnalogueModels to be used as filters.
typedef std::map<std::string, cMsgPar> BasePhyLayer::ParameterMap protected
Used at initialisation to pass the parameters to the AnalogueModel and Decider.
Member Enumeration Documentation
enum BasePhyLayer::AirFrameStates protected
The states of the receiving process for AirFrames.
Enumerator
START_RECEIVE
Start of actual receiving process of the AirFrame.
RECEIVING
AirFrame is being received.
END_RECEIVE
Receiving process over.
{
                 START_RECEIVE = 1,
                 RECEIVING,
                 END_RECEIVE
         };
enum BasePhyLayer::ProtocolIds protected
Enumerator
GENERIC
{
                 GENERIC = 0,
         };
Constructor & Destructor Documentation
BasePhyLayer::BasePhyLayer ()
                           :
         protocolId(GENERIC),
         thermalNoise(0),
         radio(0),
         decider(0),
         radioSwitchingOverTimer(0),
         txOverTimer(0),
         headerLength(-1),
         world(NULL)
 {}
BasePhyLayer::~BasePhyLayer () virtual
Free the pointer to the decider and the AnalogueModels and the Radio.
{
         //get AirFrames from ChannelInfo and delete
         //(although ChannelInfo normally owns the AirFrames it
         //is not able to cancel and delete them itself
         AirFrameVector channel;
         channelInfo.getAirFrames(0, simTime(), channel);
         for(AirFrameVector::iterator it = channel.begin();
                 it != channel.end(); ++it)
         {
                 cancelAndDelete(*it);
         }
         //free timer messages
         if(txOverTimer) {
                 cancelAndDelete(txOverTimer);
         }
         if(radioSwitchingOverTimer) {
         cancelAndDelete(radioSwitchingOverTimer);
         }
         //free thermal noise mapping
         if(thermalNoise) {
                 delete thermalNoise;
         }
         //free Decider
         if(decider != 0) {
                 delete decider;
         }
         /*
          * get a pointer to the radios RSAM again to avoid deleting it,
          * it is not created by calling new (BasePhyLayer is not the owner)!
          */
         AnalogueModel* rsamPointer = radio ? radio->getAnalogueModel() : NULL;
         //free AnalogueModels
         for(AnalogueModelList::iterator it = analogueModels.begin();
                 it != analogueModels.end(); it++) {
                 AnalogueModel* tmp = *it;
                 // do not delete the RSAM, it's not allocated by new!
                 if (tmp == rsamPointer)
                 {
                         rsamPointer = 0;
                         continue;
                 }
                 if(tmp != 0) {
                         delete tmp;
                 }
         }
         // free radio
         if(radio != 0)
         {
                 delete radio;
         }
 }
Member Function Documentation
static short BasePhyLayer::airFramePriority () inline static protected
Defines the scheduling priority of AirFrames.
AirFrames use a slightly higher priority than normal to ensure channel consistency. This means that before anything else happens at a time point t every AirFrame which ended at t has been removed and every AirFrame started at t has been added to the channel.
An example where this matters is a ChannelSenseRequest which ends at the same time as an AirFrame starts (or ends). Depending on which message is handled first the result of ChannelSenseRequest would differ.
Referenced by PhyLayer80211p::encapsMsg(), and encapsMsg().
{
                 return 10;
         }
void BasePhyLayer::cancelScheduledMessage (cMessage * msg) virtual
Tells the PhyLayer to cancel a scheduled message (AirFrame or ControlMessage).
Used by the Decider if it doesn't need to handle an AirFrame or ControlMessage again anymore.
Implements DeciderToPhyInterface.
Referenced by rescheduleMessage().
{
         if(msg->isScheduled()){
                 cancelEvent(msg);
         } else {
                 EV << "Warning: Decider wanted to cancel a scheduled message but message"
                    << " wasn't actually scheduled. Message is: " << msg << endl;
         }
 }
void BasePhyLayer::drawCurrent (double amount, int activity) virtual
Does nothing.
For an actual power supporting phy see "PhyLayerBattery".
Implements DeciderToPhyInterface.
{
         BatteryAccess::drawCurrent(amount, activity);
 }
AirFrame * BasePhyLayer::encapsMsg (cPacket * msg) protected virtual
This function encapsulates messages from the upper layer into an AirFrame and sets all necessary attributes.
Reimplemented in PhyLayer80211p.
Referenced by handleUpperMessage().
 {
         // the cMessage passed must be a MacPacket... but no cast needed here
         // MacPkt* pkt = static_cast<MacPkt*>(msg);
         // ...and must always have a ControlInfo attached (contains Signal)
         cObject* ctrlInfo = macPkt->removeControlInfo();
         assert(ctrlInfo);
         // create the new AirFrame
         AirFrame* frame = new AirFrame(macPkt->getName(), AIR_FRAME);
         // Retrieve the pointer to the Signal-instance from the ControlInfo-instance.
         // We are now the new owner of this instance.
         Signal* s = MacToPhyControlInfo::getSignalFromControlInfo(ctrlInfo);
         // make sure we really obtained a pointer to an instance
         assert(s);
         // set the members
         assert(s->getDuration() > 0);
         frame->setDuration(s->getDuration());
         // copy the signal into the AirFrame
         frame->setSignal(*s);
         //set priority of AirFrames above the normal priority to ensure
         //channel consistency (before any thing else happens at a time
         //point t make sure that the channel has removed every AirFrame
         //ended at t and added every AirFrame started at t)
         frame->setSchedulingPriority(airFramePriority());
         frame->setProtocolId(myProtocolId());
         frame->setBitLength(headerLength);
         frame->setId(world->getUniqueAirFrameId());
         frame->setChannel(radio->getCurrentChannel());
         // pointer and Signal not needed anymore
         delete s;
         s = 0;
         // delete the Control info
         delete ctrlInfo;
         ctrlInfo = 0;
         frame->encapsulate(macPkt);
         // --- from here on, the AirFrame is the owner of the MacPacket ---
         macPkt = 0;
         coreEV <<"AirFrame encapsulated, length: " << frame->getBitLength() << "\n";
         return frame;
 }
void BasePhyLayer::filterSignal (AirFrame * frame) protected virtual
Filters the passed AirFrame's Signal by every registered AnalogueModel.
Moreover, the antenna gains are calculated and added to the signal.
claim the Move pattern of the sender from the Signal
Referenced by handleAirFrameStartReceive().
{
     // determine antenna gains first
     // get POA from frame with the sender's position, orientation and antenna
     POA& senderPOA = frame->getPoa();
     // get own mobility module
     BaseMobility* ownMobility = ChannelMobilityAccessType::get(this->getParentModule());
     assert(ownMobility);
     Coord ownPos  = ownMobility->getCurrentPosition();
     Coord ownOrient = ownMobility->getCurrentOrientation();
     // compute gains at sender and receiver antenna
     double ownGain = antenna->getGain(ownPos, ownOrient, senderPOA.pos);
     double otherGain = senderPOA.antenna->getGain(senderPOA.pos, senderPOA.orientation, ownPos);
     coreEV << "Sender's antenna gain: " << otherGain << endl;
     coreEV << "Own (receiver's) antenna gain: " << ownGain << endl;
     // add the resulting total gain to the attenuations list using a ConstantSimpleConstMapping
     bool hasFrequency = frame->getSignal().getTransmissionPower()->getDimensionSet().hasDimension(Dimension::frequency());
     const DimensionSet& domain = hasFrequency ? DimensionSet::timeFreqDomain() : DimensionSet::timeDomain();
     frame->getSignal().addAttenuation(new ConstantSimpleConstMapping(domain, ownGain*otherGain));
     // go on with AnalogueModels
         if (analogueModels.empty())
                 return;
         ChannelAccess *const senderModule   = dynamic_cast<ChannelAccess *const>(frame->getSenderModule());
         ChannelAccess *const receiverModule = dynamic_cast<ChannelAccess *const>(frame->getArrivalModule());
         //const simtime_t      sStart         = frame->getSignal().getReceptionStart();
         assert(senderModule); assert(receiverModule);
         ChannelMobilityPtrType sendersMobility  = senderModule   ? senderModule->getMobilityModule()   : NULL;
         ChannelMobilityPtrType receiverMobility = receiverModule ? receiverModule->getMobilityModule() : NULL;
         const Coord sendersPos  = sendersMobility  ? sendersMobility->getCurrentPosition(/*sStart*/) : NoMobiltyPos;
         const Coord receiverPos = receiverMobility ? receiverMobility->getCurrentPosition(/*sStart*/): NoMobiltyPos;
         for(AnalogueModelList::const_iterator it = analogueModels.begin(); it != analogueModels.end(); it++)
                 (*it)->filterSignal(frame, sendersPos, receiverPos);
 }
void BasePhyLayer::finish () virtual
Only calls the deciders finish method.
Reimplemented from BaseModule.
{
         // give decider the chance to do something
         decider->finish();
 }
void BasePhyLayer::finishRadioSwitching () protected virtual
Called the moment the simulated switching process of the Radio is finished.
The Radio is set the new RadioState and the MAC Layer is sent a confirmation message.
Referenced by PhyLayer80211p::handleSelfMessage(), handleSelfMessage(), and setRadioState().
 {
         radio->endSwitch(simTime());
         sendControlMsgToMac(new cMessage("Radio switching over", RADIO_SWITCHING_OVER));
 }
AnalogueModel * BasePhyLayer::getAnalogueModelFromName (std::string name, ParameterMap & params) protected virtual
Creates and returns an instance of the AnalogueModel with the specified name.
The returned AnalogueModel has to be generated with the "new" command. The BasePhyLayer keeps the ownership of the returned AnalogueModel.
This method is used by the BasePhyLayer during initialisation to load the AnalogueModels which has been specified in the ned file.
This method has to be overridden if you want to be able to load your own AnalogueModels.
Reimplemented in PhyLayer80211p.
Referenced by PhyLayer80211p::getAnalogueModelFromName(), and initializeAnalogueModels().
{
         // add default analogue models here
         // case "RSAM", pointer is valid as long as the radio exists
         if (name == "RadioStateAnalogueModel")
         {
                 return radio->getAnalogueModel();
         }
         return 0;
 }
std::shared_ptr< Antenna > BasePhyLayer::getAntennaFromName (std::string name, ParameterMap & params) protected virtual
Creates and returns an instance of the Antenna with the specified name as a shared pointer.
This method is called during initialization to load the Antenna specified. If no special antenna has been specified, an object of the base Antenna class is instantiated, representing an isotropic antenna.
Referenced by initializeAntenna().
{
     if (name == "SampledAntenna1D") {
         return initializeSampledAntenna1D(params);
     }
     return std::make_shared<Antenna>();
 }
void BasePhyLayer::getChannelInfo (simtime_t_cref from, simtime_t_cref to, AirFrameVector & out) virtual
Fills the passed AirFrameVector with all AirFrames that intersect with the time interval [from, to].
Implements DeciderToPhyInterface.
{
         channelInfo.getAirFrames(from, to, out);
 }
ChannelState BasePhyLayer::getChannelState () virtual
Returns the current state of the channel.
See ChannelState for details.
Implements MacToPhyInterface.
{
         Enter_Method_Silent();
         assert(decider);
         return decider->getChannelState();
 }
int BasePhyLayer::getCurrentRadioChannel () virtual
Returns the channel currently used by the radio.
Implements DeciderToPhyInterface.
{
         return radio->getCurrentChannel();
 }
Decider * BasePhyLayer::getDeciderFromName (std::string name, ParameterMap & params) protected virtual
Creates and returns an instance of the Decider with the specified name.
The returned Decider has to be generated with the "new" command. The BasePhyLayer keeps the ownership of the returned Decider.
This method is used by the BasePhyLayer during initialisation to load the Decider which has been specified in the ned file.
This method has to be overridden if you want to be able to load your own Decider.
Reimplemented in PhyLayer80211p.
Referenced by PhyLayer80211p::getDeciderFromName(), and initializeDecider().
 {
         return 0;
 }
int BasePhyLayer::getNbRadioChannels () virtual
Returns the number of channels available on this radio.
Implements MacToPhyInterface.
{
         return par("nbRadioChannels");
 }
void BasePhyLayer::getParametersFromXML (cXMLElement * xmlData, ParameterMap & outputMap) private
Utility function.
Reads the parameters of a XML element and stores them in the passed ParameterMap reference.
Referenced by initializeAnalogueModels(), initializeAntenna(), and initializeDecider().
{
         cXMLElementList parameters = xmlData->getElementsByTagName("Parameter");
         for(cXMLElementList::const_iterator it = parameters.begin();
                 it != parameters.end(); it++) {
                 const char* name = (*it)->getAttribute("name");
                 const char* type = (*it)->getAttribute("type");
                 const char* value = (*it)->getAttribute("value");
                 if(name == 0 || type == 0 || value == 0)
                         throw cRuntimeError("Invalid parameter, could not find name, type or value");
                 std::string sType = type;       //needed for easier comparision
                 std::string sValue = value;     //needed for easier comparision
                 cMsgPar param(name);
                 //parse type of parameter and set value
                 if (sType == "bool") {
                         param.setBoolValue(sValue == "true" || sValue == "1");
                 } else if (sType == "double") {
                         param.setDoubleValue(strtod(value, 0));
                 } else if (sType == "string") {
                         param.setStringValue(value);
                 } else if (sType == "long") {
                         param.setLongValue(strtol(value, 0, 0));
                 } else {
                         throw cRuntimeError("Unknown parameter type: '%s'", sType.c_str());
                 }
                 //add parameter to output map
                 outputMap[name] = param;
         }
 }
int BasePhyLayer::getPhyHeaderLength () virtual
Returns the length of the phy header in bits.
Since the MAC layer has to create the signal for a transmission it has to know the total length of the packet and therefore needs the length of the phy header.
Implements MacToPhyInterface.
{
         Enter_Method_Silent();
         if (headerLength < 0)
                 return par("headerLength").longValue();
         return headerLength;
 }
int BasePhyLayer::getRadioState () virtual
Returns the current state the radio is in.
See RadioState for possible values.
This method is mainly used by the mac layer.
Implements MacToPhyInterface.
Reimplemented in PhyLayer80211p.
Referenced by PhyLayer80211p::getRadioState().
{
         Enter_Method_Silent();
         assert(radio);
         return radio->getCurrentState();
 }
simtime_t BasePhyLayer::getSimTime () virtual
Returns the current simulation time.
Implements DeciderToPhyInterface.
{
         return simTime();
 }
ConstMapping * BasePhyLayer::getThermalNoise (simtime_t_cref from, simtime_t_cref to) virtual
Returns a Mapping which defines the thermal noise in the passed time frame (in mW).
The implementing class of this method keeps ownership of the Mapping.
This implementation returns a constant mapping with the value of the "thermalNoise" module parameter
Override this method if you want to define a more complex thermal noise.
Implements DeciderToPhyInterface.
{
         if(thermalNoise)
                 thermalNoise->initializeArguments(Argument(from));
         return thermalNoise;
 }
BaseWorldUtility * BasePhyLayer::getWorldUtility () virtual
Returns a pointer to the simulations world-utility-module.
Implements DeciderToPhyInterface.
{
         return world;
 }
void BasePhyLayer::handleAirFrame (AirFrame * frame) protected virtual
Handles messages received from the channel (probably AirFrames).
Referenced by handleMessage(), PhyLayer80211p::handleSelfMessage(), and handleSelfMessage().
{
         //TODO: ask jerome to set air frame priority in his UWBIRPhy
         //assert(frame->getSchedulingPriority() == airFramePriority());
         switch(frame->getState()) {
         case START_RECEIVE:
                 handleAirFrameStartReceive(frame);
                 break;
         case RECEIVING: {
                 handleAirFrameReceiving(frame);
                 break;
         }
         case END_RECEIVE:
                 handleAirFrameEndReceive(frame);
                 break;
         default:
                 throw cRuntimeError( "Unknown AirFrame state: %s", frame->getState());
         }
 }
void BasePhyLayer::handleAirFrameEndReceive (AirFrame * msg) protected virtual
Handles incoming AirFrames with the state END_RECEIVE.
Referenced by handleAirFrame(), and handleAirFrameReceiving().
{
         coreEV << "End of Airframe with ID " << frame->getId() << "." << endl;
         simtime_t earliestInfoPoint = channelInfo.removeAirFrame(frame);
         /* clean information in the radio until earliest time-point
         *  of information in the ChannelInfo,
         *  since this time-point might have changed due to removal of
         *  the AirFrame
         */
         if(channelInfo.isChannelEmpty()) {
                 earliestInfoPoint = simTime();
                 radio->setTrackingModeTo(false);
         }
         radio->cleanAnalogueModelUntil(earliestInfoPoint);
 }
void BasePhyLayer::handleAirFrameFirstReceive (AirFrame * msg) protected
Handles incoming AirFrames with the state FIRST_RECEIVE.
void BasePhyLayer::handleAirFrameReceiving (AirFrame * msg) protected virtual
Handles incoming AirFrames with the state RECEIVING.
Referenced by handleAirFrame(), and handleAirFrameStartReceive().
{
         Signal& signal = frame->getSignal();
         simtime_t nextHandleTime = decider->processSignal(frame);
         assert(signal.getDuration() == frame->getDuration());
         simtime_t signalEndTime = signal.getReceptionStart() + frame->getDuration();
         //check if this is the end of the receiving process
         if(simTime() >= signalEndTime) {
                 frame->setState(END_RECEIVE);
                 handleAirFrameEndReceive(frame);
                 return;
         }
         //smaller zero means don't give it to me again
         if(nextHandleTime < 0) {
                 nextHandleTime = signalEndTime;
                 frame->setState(END_RECEIVE);
         //invalid point in time
         } else if(nextHandleTime < simTime() || nextHandleTime > signalEndTime) {
                 throw cRuntimeError("Invalid next handle time returned by Decider. Expected a value between current simulation time (%.2f) and end of signal (%.2f) but got %.2f",
                                                                 SIMTIME_DBL(simTime()), SIMTIME_DBL(signalEndTime), SIMTIME_DBL(nextHandleTime));
         }
         coreEV << "Handed AirFrame with ID " << frame->getId() << " to Decider. Next handling in " << nextHandleTime - simTime() << "s." << endl;
         sendSelfMessage(frame, nextHandleTime);
 }
void BasePhyLayer::handleAirFrameStartReceive (AirFrame * msg) protected virtual
Handles incoming AirFrames with the state START_RECEIVE.
Referenced by handleAirFrame().
{
         coreEV << "Received new AirFrame " << frame << " from channel." << endl;
         if(channelInfo.isChannelEmpty()) {
                 radio->setTrackingModeTo(true);
         }
         channelInfo.addAirFrame(frame, simTime());
         assert(!channelInfo.isChannelEmpty());
         if(usePropagationDelay) {
                 Signal& s = frame->getSignal();
                 simtime_t delay = simTime() - s.getSendingStart();
                 s.setPropagationDelay(delay);
         }
         assert(frame->getSignal().getReceptionStart() == simTime());
         frame->getSignal().setReceptionSenderInfo(frame);
         filterSignal(frame);
         if(decider && isKnownProtocolId(frame->getProtocolId())) {
                 frame->setState(RECEIVING);
                 //pass the AirFrame the first time to the Decider
                 handleAirFrameReceiving(frame);
         //if no decider is defined we will schedule the message directly to its end
         } else {
                 Signal& signal = frame->getSignal();
                 simtime_t signalEndTime = signal.getReceptionStart() + frame->getDuration();
                 frame->setState(END_RECEIVE);
                 sendSelfMessage(frame, signalEndTime);
         }
 }
void BasePhyLayer::handleChannelSenseRequest (cMessage * msg) protected virtual
Handles reception of a ChannelSenseRequest by forwarding it to the decider and scheduling it to the point in time returned by the decider.
Referenced by PhyLayer80211p::handleSelfMessage(), handleSelfMessage(), and handleUpperControlMessage().
{
         ChannelSenseRequest* senseReq = static_cast<ChannelSenseRequest*>(msg);
         simtime_t nextHandleTime = decider->handleChannelSenseRequest(senseReq);
         if(nextHandleTime >= simTime()) { //schedule request for next handling
                 sendSelfMessage(msg, nextHandleTime);
                 //don't throw away any AirFrames while ChannelSenseRequest is active
                 if(!channelInfo.isRecording()) {
                         channelInfo.startRecording(simTime());
                 }
         } else if(nextHandleTime >= 0.0){
                 throw cRuntimeError("Next handle time of ChannelSenseRequest returned by the Decider is smaller then current simulation time: %.2f",
                                 SIMTIME_DBL(nextHandleTime));
         }
         // else, i.e. nextHandleTime < 0.0, the Decider doesn't want to handle
         // the request again
 }
void BasePhyLayer::handleMessage (cMessage * msg) protected virtual
OMNeT++ handle message function.
Classify and forward message to subroutines.
AirFrames from channel
self scheduled AirFrames
MacPackets from MAC layer
ControllMesasges from MAC layer
self messages like TX_OVER and RADIO_SWITCHED
{
         //self messages
         if(msg->isSelfMessage()) {
                 handleSelfMessage(msg);
         //MacPkts <- MacToPhyControlInfo
         } else if(msg->getArrivalGateId() == upperLayerIn) {
                 handleUpperMessage(msg);
         //controlmessages
         } else if(msg->getArrivalGateId() == upperControlIn) {
                 handleUpperControlMessage(msg);
         //AirFrames
         } else if(msg->getKind() == AIR_FRAME){
                 handleAirFrame(static_cast<AirFrame*>(msg));
         //unknown message
         } else {
                 EV << "Unknown message received." << endl;
                 delete msg;
         }
 }
void BasePhyLayer::handleSelfMessage (cMessage * msg) protected virtual
Handles self scheduled messages.
Reimplemented in PhyLayer80211p.
Referenced by handleMessage().
{
         switch(msg->getKind()) {
         //transmission over
         case TX_OVER:
                 assert(msg == txOverTimer);
                 sendControlMsgToMac(new cMessage("Transmission over", TX_OVER));
                 break;
         //radio switch over
         case RADIO_SWITCHING_OVER:
                 assert(msg == radioSwitchingOverTimer);
                 finishRadioSwitching();
                 break;
         //AirFrame
         case AIR_FRAME:
                 handleAirFrame(static_cast<AirFrame*>(msg));
                 break;
         //ChannelSenseRequest
         case CHANNEL_SENSE_REQUEST:
                 handleChannelSenseRequest(msg);
                 break;
         default:
                 break;
         }
 }
void BasePhyLayer::handleUpperControlMessage (cMessage * msg) protected virtual
Handles messages received from the upper layer through the control gate.
Referenced by handleMessage().
{
         switch(msg->getKind()) {
         case CHANNEL_SENSE_REQUEST:
                 handleChannelSenseRequest(msg);
                 break;
         default:
                 throw cRuntimeError("Received unknown control message from upper layer!");
         }
 }
void BasePhyLayer::handleUpperMessage (cMessage * msg) protected virtual
Handles messages received from the upper layer through the data gate.
Also, attaches a POA object to the created Airframe containing information needed by the receiver for antenna gain calculation.
Referenced by handleMessage().
{
         // check if Radio is in TX state
         if (radio->getCurrentState() != Radio::TX)
         {
         delete msg;
         msg = 0;
                 throw cRuntimeError("Error: message for sending received, but radio not in state TX");
         }
         // check if not already sending
         if(txOverTimer->isScheduled())
         {
         delete msg;
         msg = 0;
                 throw cRuntimeError("Error: message for sending received, but radio already sending");
         }
         // build the AirFrame to send
         assert(dynamic_cast<cPacket*>(msg) != 0);
         AirFrame* frame = encapsMsg(static_cast<cPacket*>(msg));
         // Prepare a POA object and attach it to the created Airframe
     BaseMobility* sendersMobility = ChannelMobilityAccessType::get(this->getParentModule());
     assert(sendersMobility);
     Coord pos  = sendersMobility->getCurrentPosition();
     Coord orient = sendersMobility->getCurrentOrientation();
         POA* poa = new POA(pos, orient, antenna);
         frame->setPoa(*poa);
         // the frame is now owner of the POA object
         delete poa;
         poa = 0;
         // make sure there is no self message of kind TX_OVER scheduled
         // and schedule the actual one
         assert (!txOverTimer->isScheduled());
         sendSelfMessage(txOverTimer, simTime() + frame->getDuration());
         sendMessageDown(frame);
 }
void BasePhyLayer::initialize (int stage) protected virtual
OMNeT++ initialization function.
Read simple parameters. Read and parse xml file for decider and analogue models configuration.
Reimplemented from Veins::ChannelAccess.
Reimplemented in PhyLayer80211p.
Referenced by PhyLayer80211p::initialize().
{
         ChannelAccess::initialize(stage);
         if (stage == 0) {
                 // if using sendDirect, make sure that messages arrive without delay
                 gate("radioIn")->setDeliverOnReceptionStart(true);
                 //get gate ids
                 upperLayerIn = findGate("upperLayerIn");
                 upperLayerOut = findGate("upperLayerOut");
                 upperControlOut = findGate("upperControlOut");
                 upperControlIn = findGate("upperControlIn");
                 //read simple ned-parameters
                 //      - initialize basic parameters
                 if(par("useThermalNoise").boolValue()) {
                         double thermalNoiseVal = FWMath::dBm2mW(par("thermalNoise").doubleValue());
                         thermalNoise = new ConstantSimpleConstMapping(DimensionSet::timeDomain(),
                                                                                                                   thermalNoiseVal);
                 } else {
                         thermalNoise = 0;
                 }
                 headerLength = par("headerLength").longValue();
                 sensitivity = par("sensitivity").doubleValue();
                 sensitivity = FWMath::dBm2mW(sensitivity);
                 recordStats = par("recordStats").boolValue();
                 //      - initialize radio
                 radio = initializeRadio();
                 // get pointer to the world module
                 world = FindModule<BaseWorldUtility*>::findGlobalModule();
         if (world == NULL) {
             throw cRuntimeError("Could not find BaseWorldUtility module");
         }
         if(cc->hasPar("sat")
                    && (sensitivity - FWMath::dBm2mW(cc->par("sat").doubleValue())) < -0.000001) {
             throw cRuntimeError("Sensitivity can't be smaller than the "
                                           "signal attenuation threshold (sat) in ConnectionManager. "
                                           "Please adjust your omnetpp.ini file accordingly.");
                 }
 //      } else if (stage == 1){
                 //read complex(xml) ned-parameters
                 //      - analogue model parameters
                 initializeAnalogueModels(par("analogueModels").xmlValue());
                 //      - decider parameters
                 initializeDecider(par("decider").xmlValue());
                 //  - antenna parameters
                 initializeAntenna(par("antenna").xmlValue());
                 //initialise timer messages
                 radioSwitchingOverTimer = new cMessage("radio switching over", RADIO_SWITCHING_OVER);
                 txOverTimer = new cMessage("transmission over", TX_OVER);
         }
 }
void BasePhyLayer::initializeAnalogueModels (cXMLElement * xmlConfig) private
Initializes the AnalogueModels with the data from the passed XML-config data.
Referenced by initialize().
{
         /*
         * first of all, attach the AnalogueModel that represents the RadioState
         * to the AnalogueModelList as first element.
         */
         std::string s("RadioStateAnalogueModel");
         ParameterMap p;
         AnalogueModel* newAnalogueModel = getAnalogueModelFromName(s, p);
         if(newAnalogueModel == 0)
         {
                 throw cRuntimeError("Could not find an analogue model with the name \"%s\".", s.c_str());
         }
         else
         {
                 analogueModels.push_back(newAnalogueModel);
         }
         if(xmlConfig == 0) {
                 throw cRuntimeError("No analogue models configuration file specified.");
         }
         cXMLElementList analogueModelList = xmlConfig->getElementsByTagName("AnalogueModel");
         if(analogueModelList.empty()) {
                 throw cRuntimeError("No analogue models configuration found in configuration file.");
         }
         // iterate over all AnalogueModel-entries, get a new AnalogueModel instance and add
         // it to analogueModels
         for(cXMLElementList::const_iterator it = analogueModelList.begin();
                 it != analogueModelList.end(); it++) {
                 cXMLElement* analogueModelData = *it;
                 const char* name = analogueModelData->getAttribute("type");
                 if(name == 0) {
                         throw cRuntimeError("Could not read name of analogue model.");
                 }
                 ParameterMap params;
                 getParametersFromXML(analogueModelData, params);
                 AnalogueModel* newAnalogueModel = getAnalogueModelFromName(name, params);
                 if(newAnalogueModel == 0) {
                         throw cRuntimeError("Could not find an analogue model with the name \"%s\".", name);
                 }
                 // attach the new AnalogueModel to the AnalogueModelList
                 analogueModels.push_back(newAnalogueModel);
                 coreEV << "AnalogueModel \"" << name << "\" loaded." << endl;
         } // end iterator loop
 }
void BasePhyLayer::initializeAntenna (cXMLElement * xmlConfig) private
Initializes the Antenna with the data from the passed XML-config data.
Referenced by initialize().
{
     antenna = 0;
     if(xmlConfig == 0) {
         throw cRuntimeError("No antenna configuration file specified.");
     }
     cXMLElementList antennaList = xmlConfig->getElementsByTagName("Antenna");
     if(antennaList.empty()) {
         throw cRuntimeError("No antenna configuration found in configuration file.");
     }
     cXMLElement* antennaData;
     if(antennaList.size() > 1) {
         int num = intuniform(0, antennaList.size() - 1);
         antennaData = antennaList[num];
     } else {
         antennaData = antennaList.front();
     }
     const char* name = antennaData->getAttribute("type");
     if(name == 0) {
         throw cRuntimeError("Could not read type of antenna from configuration file.");
     }
     ParameterMap params;
     getParametersFromXML(antennaData, params);
     antenna = getAntennaFromName(name, params);
     if(antenna == 0) {
         throw cRuntimeError("Could not find an antenna with the name \"%s\".", name);
     }
     const char* id = antennaData->getAttribute("id");
     coreEV << "Antenna \"" << name << "\" with ID \"" << id << "\" loaded." << endl;
 }
void BasePhyLayer::initializeDecider (cXMLElement * xmlConfig) private
Initializes the Decider with the data from the passed XML-config data.
Referenced by initialize().
{
         decider = 0;
         if(xmlConfig == 0) {
                 throw cRuntimeError("No decider configuration file specified.");
         }
         cXMLElementList deciderList = xmlConfig->getElementsByTagName("Decider");
         if(deciderList.empty()) {
                 throw cRuntimeError("No decider configuration found in configuration file.");
         }
         if(deciderList.size() > 1) {
                 throw cRuntimeError("More than one decider configuration found in configuration file.");
         }
         cXMLElement* deciderData = deciderList.front();
         const char* name = deciderData->getAttribute("type");
         if(name == 0) {
                 throw cRuntimeError("Could not read type of decider from configuration file.");
         }
         ParameterMap params;
         getParametersFromXML(deciderData, params);
         decider = getDeciderFromName(name, params);
         if(decider == 0) {
                 throw cRuntimeError("Could not find a decider with the name \"%s\".", name);
         }
         coreEV << "Decider \"" << name << "\" loaded." << endl;
 }
Radio * BasePhyLayer::initializeRadio () protected virtual
Initializes and returns the radio class to use.
Can be overridden by sub-classing phy layers to use their own Radio implementations.
Referenced by initialize().
{
         int initialRadioState = par("initialRadioState").longValue();
         double radioMinAtt = par("radioMinAtt").doubleValue();
         double radioMaxAtt = par("radioMaxAtt").doubleValue();
         int nbRadioChannels = readPar("nbRadioChannels", 1);
         int initialRadioChannel = readPar("initialRadioChannel", 0);
         Radio* radio = Radio::createNewRadio(recordStats, initialRadioState,
                                                                                  radioMinAtt, radioMaxAtt,
                                                                                  initialRadioChannel, nbRadioChannels);
         //      - switch times to TX
         //if no RX to TX defined asume same time as sleep to TX
         radio->setSwitchTime(Radio::RX, Radio::TX, (hasPar("timeRXToTX") ? par("timeRXToTX") : par("timeSleepToTX")).doubleValue());
         //if no sleep to TX defined asume same time as RX to TX
         radio->setSwitchTime(Radio::SLEEP, Radio::TX, (hasPar("timeSleepToTX") ? par("timeSleepToTX") : par("timeRXToTX")).doubleValue());
         //      - switch times to RX
         //if no TX to RX defined asume same time as sleep to RX
         radio->setSwitchTime(Radio::TX, Radio::RX, (hasPar("timeTXToRX") ? par("timeTXToRX") : par("timeSleepToRX")).doubleValue());
         //if no sleep to RX defined asume same time as TX to RX
         radio->setSwitchTime(Radio::SLEEP, Radio::RX, (hasPar("timeSleepToRX") ? par("timeSleepToRX") : par("timeTXToRX")).doubleValue());
         //      - switch times to sleep
         //if no TX to sleep defined asume same time as RX to sleep
         radio->setSwitchTime(Radio::TX, Radio::SLEEP, (hasPar("timeTXToSleep") ? par("timeTXToSleep") : par("timeRXToSleep")).doubleValue());
         //if no RX to sleep defined asume same time as TX to sleep
         radio->setSwitchTime(Radio::RX, Radio::SLEEP, (hasPar("timeRXToSleep") ? par("timeRXToSleep") : par("timeTXToSleep")).doubleValue());
         return radio;
 }
std::shared_ptr< Antenna > BasePhyLayer::initializeSampledAntenna1D (ParameterMap & params) protected virtual
Creates and returns an instance of the SampledAntenna1D class as a shared pointer.
The given parameters (i.e. samples and optional randomness parameters) are evaluated and given to the antenna's constructor.
Referenced by getAntennaFromName().
{
     // get samples of the modeled antenna and put them in a vector
     ParameterMap::iterator it = params.find("samples");
     std::vector<double> values;
     if (it != params.end())
     {
         std::string buf;
         std::stringstream samplesStream(it->second.stringValue());
         while (samplesStream >> buf){
             values.push_back(stod(buf));
         }
     } else {
         throw cRuntimeError("BasePhyLayer::initializeSampledAntenna1D(): No samples specified for this antenna. \
                            Please adjust your xml file accordingly.");
     }
     // get optional random offsets for the antenna's samples
     it = params.find("random-offsets");
     std::string offsetType = "";
     std::vector<double> offsetParams;
     if (it != params.end())
     {
         std::string buf;
         std::stringstream offsetStream(it->second.stringValue());
         offsetStream >> offsetType;
         while (offsetStream >> buf){
             offsetParams.push_back(stod(buf));
         }
     }
     // get optional random rotation of the whole pattern
     it = params.find("random-rotation");
     std::string rotationType = "";
     std::vector<double> rotationParams;
     if (it != params.end())
     {
         std::string buf;
         std::stringstream rotationStream(it->second.stringValue());
         rotationStream >> rotationType;
         while (rotationStream >> buf){
             rotationParams.push_back(stod(buf));
         }
     }
     return std::make_shared<SampledAntenna1D>(values, offsetType, offsetParams, rotationType, rotationParams, this->getRNG(0));
 }
virtual bool BasePhyLayer::isKnownProtocolId (int id) inline protected virtual
Returns true if the protocol with the passed identifier is decodeable by the decider.
If the protocol with the passed id is not understood by this phy layers decider the according AirFrame is not passed to the it but only is added to channel info to be available as interference to the decider.
Default implementation checks only if the passed id is the same as the one returned by "myProtocolId()".
Parameters
id The identifier of the protocol of an AirFrame.
Returns
Returns true if the passed protocol id is supported by this phy- layer.
Referenced by handleAirFrameStartReceive().
 { return id == myProtocolId(); }
virtual int BasePhyLayer::myProtocolId () inline protected virtual
Returns the identifier of the protocol this phy uses to send messages.
Returns
An integer representing the identifier of the used protocol.
Referenced by PhyLayer80211p::encapsMsg(), and encapsMsg().
 { return protocolId; }
template<class T > template bool BasePhyLayer::readPar< bool > (const char * parName, const T defaultValue) protected
Reads and returns the parameter with the passed name.
If the parameter couldn't be found the value of defaultValue is returned.
Parameters
parName - the name of the ned-parameter
defaultValue - the value to be returned if the parameter couldn't be found
Referenced by initializeRadio().
{
         if(hasPar(parName))
                 return par(parName);
         else
                 return defaultValue;
 }
void BasePhyLayer::recordScalar (const char * name, double value, const char * unit = NULL) virtual
Records a double into the scalar result file.
Implements the method from DeciderToPhyInterface, method-calls are forwarded to OMNeT-method 'recordScalar'.
Implements DeciderToPhyInterface.
{
         ChannelAccess::recordScalar(name, value, unit);
 }
void BasePhyLayer::rescheduleMessage (cMessage * msg, simtime_t_cref t) virtual
Tells the PhyLayer to reschedule a message (AirFrame or ControlMessage).
Used by the Decider if it has to handle an AirFrame or an control message earlier than it has returned to the PhyLayer the last time the Decider handled that message.
Implements DeciderToPhyInterface.
{
         cancelScheduledMessage(msg);
         scheduleAt(t, msg);
 }
void BasePhyLayer::sendControlMessageUp (cMessage * msg) protected
Sends the passed control message to the upper layer.
Referenced by sendControlMsgToMac().
{
         send(msg, upperControlOut);
 }
void BasePhyLayer::sendControlMsgToMac (cMessage * msg) virtual
Called by the Decider to send a control message to the MACLayer.
This function can be used to answer a ChannelSenseRequest to the MACLayer
Implements DeciderToPhyInterface.
Referenced by finishRadioSwitching(), PhyLayer80211p::handleSelfMessage(), and handleSelfMessage().
{
         if(msg->getKind() == CHANNEL_SENSE_REQUEST) {
                 if(channelInfo.isRecording()) {
                         channelInfo.stopRecording();
                 }
         }
         sendControlMessageUp(msg);
 }
void BasePhyLayer::sendMacPktUp (cMessage * pkt) protected
Sends the passed MacPkt to the upper layer.
Referenced by sendUp().
{
         send(pkt, upperLayerOut);
 }
void BasePhyLayer::sendMessageDown (AirFrame * pkt) protected
Sends the passed AirFrame to the channel.
Referenced by handleUpperMessage().
{
         sendToChannel(msg);
 }
void BasePhyLayer::sendSelfMessage (cMessage * msg, simtime_t_cref time) protected
Schedule self message to passed point in time.
Referenced by handleAirFrameReceiving(), handleAirFrameStartReceive(), handleChannelSenseRequest(), handleUpperMessage(), and setRadioState().
{
         //TODO: maybe delete this method because it doesn't makes much sense,
         //              or change it to "scheduleIn(msg, timeDelta)" which schedules
         //              a message to +timeDelta from current time
         scheduleAt(time, msg);
 }
void BasePhyLayer::sendUp (AirFrame * packet, DeciderResult * result) virtual
Called to send an AirFrame with DeciderResult to the MACLayer.
When a packet is completely received and not noise, the Decider call this function to send the packet together with the corresponding DeciderResult up to MACLayer
Implements DeciderToPhyInterface.
{
         coreEV << "Decapsulating MacPacket from Airframe with ID " << frame->getId() << " and sending it up to MAC." << endl;
         cMessage* packet = frame->decapsulate();
         assert(packet);
         setUpControlInfo(packet, result);
         sendMacPktUp(packet);
 }
void BasePhyLayer::setCurrentRadioChannel (int newRadioChannel) virtual
Sets the channel currently used by the radio.
Implements MacToPhyInterface.
{
         if(txOverTimer && txOverTimer->isScheduled()) {
                 EV_WARN << "Switched channel while sending an AirFrame. The effects this would have on the transmission are not simulated by the BasePhyLayer!";
         }
         radio->setCurrentChannel(newRadioChannel);
         decider->channelChanged(newRadioChannel);
         coreEV << "Switched radio to channel " << newRadioChannel << endl;
 }
simtime_t BasePhyLayer::setRadioState (int rs) virtual
Tells the BasePhyLayer to switch to the specified radio state.
The switching process can take some time depending on the specified switching times in the ned file.
Returns
-1: Error code if the Radio is currently switching else: switching time from the current RadioState to the new RadioState
Implements MacToPhyInterface.
Reimplemented in PhyLayer80211p.
Referenced by PhyLayer80211p::setRadioState().
{
         Enter_Method_Silent();
         assert(radio);
         if(txOverTimer && txOverTimer->isScheduled()) {
                 EV_WARN << "Switched radio while sending an AirFrame. The effects this would have on the transmission are not simulated by the BasePhyLayer!";
         }
         simtime_t switchTime = radio->switchTo(rs, simTime());
         //invalid switch time, we are probably already switching
         if(switchTime < 0)
                 return switchTime;
         // if switching is done in exactly zero-time no extra self-message is scheduled
         if (switchTime == 0.0)
         {
                 // TODO: in case of zero-time-switch, send no control-message to mac!
                 // maybe call a method finishRadioSwitchingSilent()
                 finishRadioSwitching();
         } else
         {
                 sendSelfMessage(radioSwitchingOverTimer, simTime() + switchTime);
         }
         return switchTime;
 }
cObject *const BasePhyLayer::setUpControlInfo (cMessage *const pMsg, DeciderResult *const pDeciderResult) virtual
Attaches a "control info" (PhyToMac) structure (object) to the message pMsg.
This is most useful when passing packets between protocol layers of a protocol stack, the control info will contain the decider result.
The "control info" object will be deleted when the message is deleted. Only one "control info" structure can be attached (the second setL3ToL2ControlInfo() call throws an error).
Parameters
pMsg The message where the "control info" shall be attached.
pSrcAddr The MAC address of the message receiver.
Referenced by sendUp().
 {
         return PhyToMacControlInfo::setControlInfo(pMsg, pDeciderResult);
 }
Member Data Documentation
AnalogueModelList BasePhyLayer::analogueModels protected
List of the analogue models to use.
Referenced by filterSignal(), PhyLayer80211p::initialize(), initializeAnalogueModels(), and ~BasePhyLayer().
std::shared_ptr<Antenna> BasePhyLayer::antenna protected
Shared pointer to the Antenna used for this node.
It needs to be a shared pointer as a possible receiver could still need the antenna for gain calculation even if this node has already disappeared. The antenna will be deleted when nothing is pointing to it any more.
Referenced by filterSignal(), handleUpperMessage(), and initializeAntenna().
ChannelInfo BasePhyLayer::channelInfo protected
Channel info keeps track of received AirFrames and provides information about currently active AirFrames at the channel.
Referenced by getChannelInfo(), handleAirFrameEndReceive(), handleAirFrameStartReceive(), handleChannelSenseRequest(), sendControlMsgToMac(), and ~BasePhyLayer().
Decider* BasePhyLayer::decider protected
Pointer to the decider module.
Referenced by PhyLayer80211p::changeListeningFrequency(), finish(), getChannelState(), handleAirFrameReceiving(), handleAirFrameStartReceive(), handleChannelSenseRequest(), PhyLayer80211p::handleSelfMessage(), initializeDecider(), PhyLayer80211p::setCCAThreshold(), setCurrentRadioChannel(), PhyLayer80211p::setRadioState(), and ~BasePhyLayer().
int BasePhyLayer::headerLength protected
Stores the length of the phy header in bits.
Referenced by PhyLayer80211p::encapsMsg(), encapsMsg(), getPhyHeaderLength(), and initialize().
int BasePhyLayer::protocolId protected
Referenced by PhyLayer80211p::getDeciderFromName().
Radio* BasePhyLayer::radio protected
The state machine storing the current radio state (TX, RX, SLEEP).
Referenced by PhyLayer80211p::encapsMsg(), encapsMsg(), finishRadioSwitching(), getAnalogueModelFromName(), getCurrentRadioChannel(), getRadioState(), handleAirFrameEndReceive(), handleAirFrameStartReceive(), handleUpperMessage(), initialize(), initializeRadio(), setCurrentRadioChannel(), setRadioState(), and ~BasePhyLayer().
cMessage* BasePhyLayer::radioSwitchingOverTimer protected
Self message scheduled to the point in time when the switching process of the radio is over.
Referenced by PhyLayer80211p::handleSelfMessage(), handleSelfMessage(), initialize(), setRadioState(), and ~BasePhyLayer().
bool BasePhyLayer::recordStats protected
Stores if tracking of statistics (esp.
cOutvectors) is enabled.
Referenced by initialize(), and initializeRadio().
double BasePhyLayer::sensitivity protected
The sensitivity describes the minimum strength a signal must have to be received.
Referenced by initialize(), and PhyLayer80211p::initializeDecider80211p().
ConstantSimpleConstMapping* BasePhyLayer::thermalNoise protected
Defines the strength of the thermal noise.
Referenced by getThermalNoise(), initialize(), and ~BasePhyLayer().
cMessage* BasePhyLayer::txOverTimer protected
Self message scheduled to the point in time when the transmission of an AirFrame is over.
Referenced by PhyLayer80211p::handleSelfMessage(), handleSelfMessage(), handleUpperMessage(), initialize(), setCurrentRadioChannel(), setRadioState(), and ~BasePhyLayer().
int BasePhyLayer::upperControlIn protected
The id of the in-control gate from the Mac layer.
Referenced by handleMessage(), and initialize().
int BasePhyLayer::upperControlOut protected
The id of the out-control gate to the Mac layer.
Referenced by initialize(), and sendControlMessageUp().
int BasePhyLayer::upperLayerIn protected
The id of the in-data gate from the Mac layer.
Referenced by handleMessage(), and initialize().
int BasePhyLayer::upperLayerOut protected
The id of the out-data gate to the Mac layer.
Referenced by initialize(), and sendMacPktUp().
BaseWorldUtility* BasePhyLayer::world protected
Pointer to the World Utility, to obtain some global information.
Referenced by PhyLayer80211p::encapsMsg(), encapsMsg(), PhyLayer80211p::getAnalogueModelFromName(), getWorldUtility(), initialize(), PhyLayer80211p::initializeBreakpointPathlossModel(), PhyLayer80211p::initializeSimpleObstacleShadowing(), and PhyLayer80211p::initializeSimplePathlossModel().
The documentation for this class was generated from the following files:
BasePhyLayer.h
BasePhyLayer.cc