Veins Framework: Veins::TraCICommandInterface::Polygon Class Reference
Veins::TraCICommandInterface::Polygon Class Reference
#include <TraCICommandInterface.h>
Public Member Functions
Polygon (TraCICommandInterface *traci, std::string polyId)
std::string getTypeId ()
std::list< Coord > getShape ()
void setShape (const std::list< Coord > &points)
void remove (int32_t layer)
Protected Attributes
TraCICommandInterface * traci
TraCIConnection * connection
std::string polyId
Constructor & Destructor Documentation
Veins::TraCICommandInterface::Polygon::Polygon (TraCICommandInterface * traci, std::string polyId) inline
                                                                                         : traci(traci), polyId(polyId) {
                                         connection = &traci->connection;
                                 }
Member Function Documentation
std::list< Coord > Veins::TraCICommandInterface::Polygon::getShape ()
Referenced by Veins::TraCITestApp::handlePositionUpdate(), and Veins::TraCIScenarioManager::init_traci().
{
         return traci->genericGetCoordList(CMD_GET_POLYGON_VARIABLE, polyId, VAR_SHAPE, RESPONSE_GET_POLYGON_VARIABLE);
 }
std::string Veins::TraCICommandInterface::Polygon::getTypeId ()
Referenced by Veins::TraCITestApp::handlePositionUpdate(), and Veins::TraCIScenarioManager::init_traci().
{
         return traci->genericGetString(CMD_GET_POLYGON_VARIABLE, polyId, VAR_TYPE, RESPONSE_GET_POLYGON_VARIABLE);
 }
void Veins::TraCICommandInterface::Polygon::remove (int32_t layer)
{
         TraCIBuffer p;
         p << static_cast<uint8_t>(REMOVE) << polyId;
         p << static_cast<uint8_t>(TYPE_INTEGER) << layer;
         TraCIBuffer buf = connection->query(CMD_SET_POLYGON_VARIABLE, p);
         ASSERT(buf.eof());
 }
void Veins::TraCICommandInterface::Polygon::setShape (const std::list< Coord > & points)
Referenced by Veins::TraCITestApp::handlePositionUpdate().
{
         TraCIBuffer buf;
         uint8_t count = static_cast<uint8_t>(points.size());
         buf << static_cast<uint8_t>(VAR_SHAPE) << polyId << static_cast<uint8_t>(TYPE_POLYGON) << count;
         for (std::list<Coord>::const_iterator i = points.begin(); i != points.end(); ++i) {
                 const TraCICoord& pos = connection->omnet2traci(*i);
                 buf << static_cast<double>(pos.x) << static_cast<double>(pos.y);
         }
         TraCIBuffer obuf = connection->query(CMD_SET_POLYGON_VARIABLE, buf);
         ASSERT(obuf.eof());
 }
Member Data Documentation
TraCIConnection* Veins::TraCICommandInterface::Polygon::connection protected
Referenced by Polygon().
std::string Veins::TraCICommandInterface::Polygon::polyId protected
TraCICommandInterface* Veins::TraCICommandInterface::Polygon::traci protected
The documentation for this class was generated from the following files:
TraCICommandInterface.h
TraCICommandInterface.cc