Veins Framework: ChannelSenseRequest Class Reference
ChannelSenseRequest Class Reference
Class generated from veins/base/messages/ChannelSenseRequest.msg:46 by nedtool.
#include <ChannelSenseRequest_m.h>
Public Member Functions
ChannelSenseRequest (const char *name=nullptr, short kind=0)
ChannelSenseRequest (const ChannelSenseRequest &other)
virtual ~ChannelSenseRequest ()
ChannelSenseRequest & operator= (const ChannelSenseRequest &other)
virtual ChannelSenseRequest * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getSenseMode () const
virtual void setSenseMode (int senseMode)
virtual ::omnetpp::simtime_t getSenseTimeout () const
virtual void setSenseTimeout (::omnetpp::simtime_t senseTimeout)
virtual ChannelState & getResult ()
virtual const ChannelState & getResult () const
virtual void setResult (const ChannelState &result)
Protected Member Functions
bool operator== (const ChannelSenseRequest &)
Protected Attributes
int senseMode
::omnetpp::simtime_t senseTimeout
ChannelState result
Private Member Functions
void copy (const ChannelSenseRequest &other)
Detailed Description
Class generated from veins/base/messages/ChannelSenseRequest.msg:46 by nedtool.
//
// The ChannelSenseRequest is a control packet from the
// MAC layer to the physical layer. In contrast to the
// "getChannelState()" method of the MacToPhyInterface
// which imediatly returns the current ChannelState
// the ChannelSenseRequest tells the physical layers decider
// to sense over a period of time before sending back
// the request together with the ChannelState over this period.
//
// Every ChannelSenseRequest sent to the physical layer
// has to define a SenseMode and a timeout.
// The timeout defines after how much seconds the request
// should be sent back to the MAC layer at latest.
// The SenseMode tells the physical layers the purpose of the
// sense. The SenseModes "UNTIL_IDLE" and "UNTIL_BUSY" are
// telling it to inform the MAC layer as soon as the
// channel turns idle/busy by sending the request back to it.
// If the channel state does not change the request is sent
// back after the timeout.
// While "UNTIL_IDLE" and "UNTIL_BUSY" can be used as pure
// conveniance functions which don't necessarily represent a
// real channel sense, "UNTIL_TIMEOUT" always represents a real
// channel sensing of the MAC over a fixed period of time
// where the request together with the result will be always sent
// back after the timeout.
//
// The request returned to the MAC layer holds the result
// in the form of a ChannelState object. How the idle and
// rssi info contained in the ChannelState are calculated
// and interpreted depends on the Decider.
//
packet ChannelSenseRequest
{
    int senseMode @enum(SenseMode);    // defines the sensing mode (see SenseMode enum)
    simtime_t senseTimeout;             // Time to listen on the channel
    ChannelState result;                        // The result of the request containing the current state of the channel.
                                                                        // See ChannelState for details.
}
Constructor & Destructor Documentation
ChannelSenseRequest::ChannelSenseRequest (const char * name = nullptr, short kind = 0)
Referenced by dup().
ChannelSenseRequest::ChannelSenseRequest (const ChannelSenseRequest & other)
virtual ChannelSenseRequest::~ChannelSenseRequest () virtual
Member Function Documentation
void ChannelSenseRequest::copy (const ChannelSenseRequest & other) private
virtual ChannelSenseRequest* ChannelSenseRequest::dup () const inline override virtual
 {return new ChannelSenseRequest(*this);}
virtual ChannelState& ChannelSenseRequest::getResult () virtual
virtual const ChannelState& ChannelSenseRequest::getResult () const inline virtual
Referenced by getResult().
 {return const_cast<ChannelSenseRequest*>(this)->getResult();}
virtual int ChannelSenseRequest::getSenseMode () const virtual
Referenced by SNRThresholdDecider::canAnswerCSR(), and BaseDecider::canAnswerCSR().
virtual ::omnetpp::simtime_t ChannelSenseRequest::getSenseTimeout () const
Referenced by SNRThresholdDecider::canAnswerCSR(), and BaseDecider::canAnswerCSR().
ChannelSenseRequest& ChannelSenseRequest::operator= (const ChannelSenseRequest & other)
bool ChannelSenseRequest::operator== (const ChannelSenseRequest &) protected
virtual void ChannelSenseRequest::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by doParsimPacking().
virtual void ChannelSenseRequest::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by doParsimUnpacking().
virtual void ChannelSenseRequest::setResult (const ChannelState & result) virtual
Referenced by SNRThresholdDecider::answerCSR(), and BaseDecider::answerCSR().
virtual void ChannelSenseRequest::setSenseMode (int senseMode) virtual
virtual void ChannelSenseRequest::setSenseTimeout (::omnetpp::simtime_t senseTimeout) virtual
Member Data Documentation
ChannelState ChannelSenseRequest::result protected
int ChannelSenseRequest::senseMode protected
::omnetpp::simtime_t ChannelSenseRequest::senseTimeout protected
The documentation for this class was generated from the following file:
ChannelSenseRequest_m.h