Veins Framework: Veins Namespace Reference
Veins Namespace Reference
Basic class for all physical layers, please don't touch!!
Classes
class ChannelAccess
class AirFrame
Class generated from veins/base/messages/AirFrame.msg:35 by nedtool.
class BatteryAccess
class Radio
class TraCITestApp
class TraCIBuffer
Byte-buffer that stores values in TraCI byte-order.
class TraCIColor
TraCI compatible color container.
class TraCICommandInterface
struct traci2omnet_functor
class TraCIConnection
struct TraCICoord
Coord equivalent for storing TraCI coordinates.
class TraCILauncher
class TraCIMobility
class TraCIMobilityAccess
class TraCIScenarioManager
class TraCIScenarioManagerAccess
class TraCIScenarioManagerForker
class TraCIScenarioManagerForkerAccess
class TraCIScenarioManagerLaunchd
class TraCIScenarioManagerLaunchdAccess
class TraCIScreenRecorder
class Obstacle
class ObstacleControl
class ObstacleControlAccess
class AnnotationDummy
class AnnotationManager
class AnnotationManagerAccess
Functions
void doParsimPacking (omnetpp::cCommBuffer *b, const AirFrame &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, AirFrame &obj)
bool isBigEndian ()
SOCKET socket (void *ptr)
std::string makeTraCICommand (uint8_t commandId, const TraCIBuffer &buf=TraCIBuffer())
returns byte-buffer containing a TraCI command with optional parameters
Detailed Description
Basic class for all physical layers, please don't touch!!
manages annotations on the OMNeT++ canvas.
AnnotationDummy is just a workaround to visualize annotations.
ObstacleControl models obstacles that block radio transmissions.
stores information about an Obstacle for ObstacleControl
Simple support module to take (a series of) screenshots of a simulation running in the TraCI server.
Extends the TraCIScenarioManager for use with sumo-launchd.py and SUMO.
Extends the TraCIScenarioManager to automatically fork an instance of SUMO when needed.
Creates and moves nodes controlled by a TraCI server.
Used in modules created by the TraCIScenarioManager.
Launches a program (the TraCI server) when instantiated.
FIXME.
The class that represents the Radio as a state machine.
Extends BaseModule by several methods which provide access to the battery module.
This class is not supposed to work on its own, but it contains functions and lists that cooperate with ConnectionManager to handle the dynamically created gates. This means EVERY physical layer (the lowest layer in a host) has to be derived from this class!!!!
Please don't touch this class.
Author
Marc Loebbers
Karl Wessel
The Radio creates and updates its corresponding RadioStateAnalogueModel, that is a filter representing the radios attenuation to a Signal depending on the RadioState over time.
For this basic version we assume a minimal attenuation when the Radio is in state RX, and a maximum attenuation otherwise.
A state-machine-diagram for Radio, RadioStateAnalogueModel and ChannelInfo showing how they work together under control of BasePhyLayer as well as some documentation on how RadioStateAnalogueModel works is available in phyLayer.
See the Veins website for a tutorial, documentation, and publications .
Author
Christoph Sommer
See Also
TraCIMobility
TraCIScenarioManager
This module relies on the TraCIScenarioManager for state updates and can not be used on its own.
See the Veins website for a tutorial, documentation, and publications .
Author
Christoph Sommer, David Eckhoff, Luca Bedogni, Bastian Halmos, Stefan Joerer
See Also
TraCIScenarioManager
TraCIScenarioManagerLaunchd
If the server is a SUMO road traffic simulation, you can use the TraCIScenarioManagerLaunchd module and sumo-launchd.py script instead.
All nodes created thus must have a TraCIMobility submodule.
See the Veins website for a tutorial, documentation, and publications .
Author
Christoph Sommer, David Eckhoff, Falko Dressler, Zheng Yao, Tobias Mayer, Alvaro Torres Cortes, Luca Bedogni
See Also
TraCIMobility
TraCIScenarioManagerLaunchd
All other functionality is provided by the TraCIScenarioManager.
See the Veins website for a tutorial, documentation, and publications .
Author
Christoph Sommer, Florian Hagenauer
See Also
TraCIMobility
TraCIScenarioManager
Connects to a running instance of the sumo-launchd.py script to automatically launch/kill SUMO when the simulation starts/ends.
All other functionality is provided by the TraCIScenarioManager.
See the Veins website for a tutorial, documentation, and publications .
Author
Christoph Sommer, David Eckhoff
See Also
TraCIMobility
TraCIScenarioManager
Note that the TraCI server needs to be run in GUI mode and support taking screenshots for this to work.
The screenshots can then be converted to a video using something along the lines of mencoder 'mf://results/screenshot-*.png' -mf w=800:h=600:fps=25:type=png -ovc lavc -lavcopts vcodec=mpeg4:mbd=2:trell -oac copy -o output.avi
See the Veins website for a tutorial, documentation, and publications .
Author
Christoph Sommer
See Also
TraCIScenarioManager
Each Obstacle is a polygon. Transmissions that cross one of the polygon's lines will have their receive power set to zero.
Author
Christoph Sommer
Function Documentation
void Veins::doParsimPacking (omnetpp::cCommBuffer * b, const AirFrame & obj) inline
 {obj.parsimPack(b);}
void Veins::doParsimUnpacking (omnetpp::cCommBuffer * b, AirFrame & obj) inline
 {obj.parsimUnpack(b);}
bool Veins::isBigEndian ()
Referenced by Veins::TraCIBuffer::read(), and Veins::TraCIBuffer::write().
                    {
         short a = 0x0102;
         unsigned char *p_a = reinterpret_cast<unsigned char*>(&a);
         return (p_a[0] == 0x01);
 }
std::string Veins::makeTraCICommand (uint8_t commandId, const TraCIBuffer & buf)
returns byte-buffer containing a TraCI command with optional parameters
Referenced by Veins::TraCIScenarioManagerLaunchd::init_traci(), Veins::TraCIConnection::query(), and Veins::TraCIConnection::queryOptional().
{
         if (sizeof(uint8_t) + sizeof(uint8_t) + buf.str().length() > 0xFF) {
                 uint32_t len = sizeof(uint8_t) + sizeof(uint32_t) + sizeof(uint8_t) + buf.str().length();
                 return (TraCIBuffer() << static_cast<uint8_t>(0) << len << commandId).str() + buf.str();
         }
         uint8_t len = sizeof(uint8_t) + sizeof(uint8_t) + buf.str().length();
         return (TraCIBuffer() << len << commandId).str() + buf.str();
 }
SOCKET Veins::socket (void * ptr)
Referenced by Veins::TraCIConnection::connect(), Veins::TraCIConnection::receiveMessage(), Veins::TraCIConnection::sendMessage(), Veins::TraCIScenarioManagerForker::startServer(), and Veins::TraCIConnection::~TraCIConnection().
 {
         ASSERT(ptr);
         return *static_cast<SOCKET*>(ptr);
 }